module proof.DGG.Catchup.StructuralGeneratedFrameGeometryDef where

-- File Charter:
--   * Packages the target-frame geometry generated by strict structural peels.
--   * Records generator-indexed conversion typing and the neutral target-only
--     generator positions consumed by structural spine typing.
--   * Keeps the geometry statement separate from the absorption-chain
--     constructors so each strict peel can provide one reusable witness.

import Data.Fin as Fin
open import Data.Nat using (suc)
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Types using (Ty; TyVar; ＇_; ⇑ᵗ; _[_]ᵗ)
open import Conversion using (Conv↑; Conv↓; 〖_,_↑_〗)
import Conversion as Conv
import proof.DGG.CtxImp as CTX
open import proof.DGG.ConversionPivotAlignment using
  (generator-absent; revealGeneratorPosition; concealGeneratorPosition)


record StructuralAllGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTX.World Δᴸ Δᴿ Δ)
    (Aₛ : Ty Δᴸ)
    (C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ) : Set₁ where
  field
    qCast : Aₛ CTX.⊑ᵂ⟨ W ⟩ C [ ＇ X ]ᵗ


record StructuralRevealGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTX.World Δᴸ (suc Δᴿ) Δ)
    (B C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ)
    (c : Conv↑ (suc Δᴿ) C B) : Set₁ where
  field
    X₁ : TyVar (suc Δᴿ)
    R₁ : Ty (suc Δᴿ)
    targetConversion₁ : CTX.targetStoreʷ W Conv.⊢↑[ X₁ ⦂ R₁ ] c
    targetPosition₁ : revealGeneratorPosition targetConversion₁
      ≡ generator-absent

    X₂ : TyVar (suc Δᴿ)
    R₂ : Ty (suc Δᴿ)
    targetConversion₂ : CTX.targetStoreʷ W Conv.⊢↑[ X₂ ⦂ R₂ ]
      〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗
    targetPosition₂ : revealGeneratorPosition targetConversion₂
      ≡ generator-absent


record StructuralConcealGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTX.World Δᴸ (suc Δᴿ) Δ)
    (B C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ)
    (c : Conv↓ (suc Δᴿ) C B) : Set₁ where
  field
    X₁ : TyVar (suc Δᴿ)
    R₁ : Ty (suc Δᴿ)
    targetConversion₁ : CTX.targetStoreʷ W Conv.⊢↓[ X₁ ⦂ R₁ ] c
    targetPosition₁ : concealGeneratorPosition targetConversion₁
      ≡ generator-absent

    X₂ : TyVar (suc Δᴿ)
    R₂ : Ty (suc Δᴿ)
    targetConversion₂ : CTX.targetStoreʷ W Conv.⊢↑[ X₂ ⦂ R₂ ]
      〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗
    targetPosition₂ : revealGeneratorPosition targetConversion₂
      ≡ generator-absent
