module proof.DGG.Catchup.StructuralGeneratedFrameGeometryDef where

-- File Charter:
--   * Packages the target-frame geometry generated by strict structural peels.
--   * Records the endpoint and rebased-premise witnesses consumed by target
--     frame absorption.
--   * Keeps the geometry statement separate from the absorption-chain
--     constructors so each strict peel can provide one reusable witness.

import Data.Fin as Fin
open import Data.Nat using (suc)
open import Data.Maybe using (Maybe)
open import Data.Product using (Σ-syntax)

open import Types using (Ty; TyVar; ＇_; ⇑ᵗ; _[_]ᵗ)
open import Conversion using (Conv↑; Conv↓; replaceTy; 〖_,_↑_〗)
open import CastTerms using (Term; Value; _↑_; _↓_)
open import Reduction using (keep; _—→[_]_)
import proof.DGG.CastTermImprecision2 as CTI2


record StructuralAllGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTI2.World Δᴸ Δᴿ Δ)
    (Aₛ : Ty Δᴸ)
    (C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ) : Set₁ where
  field
    qCast : Aₛ CTI2.⊑ᵂ⟨ W ⟩ C [ ＇ X ]ᵗ


record StructuralRevealGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTI2.World Δᴸ (suc Δᴿ) Δ)
    (γ : CTI2.CtxImp W)
    (Aₛ : Ty Δᴸ)
    (B C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ)
    (c : Conv↑ (suc Δᴿ) C B) : Set₁ where
  field
    Wᵖ₁ : CTI2.World Δᴸ (suc Δᴿ) Δ
    γᵖ₁ : CTI2.CtxImp Wᵖ₁
    X₁? : Maybe (TyVar (suc Δᴿ))
    mono₁ : CTI2.ImpEnvMono W Wᵖ₁
    rebase₁ : CTI2.RebaseAtᴿ W Wᵖ₁ X₁?
    same₁ : CTI2.SameCtx γ γᵖ₁
    targetConversion₁ : CTI2.targetStoreʷ W CTI2.⊢↑[ X₁? ] c
    transport₁ :
      ∀ {M : Term Δᴸ} {N : Term (suc Δᴿ)}
        {p : Aₛ CTI2.⊑ᵂ⟨ W ⟩ C}
      → W CTI2.∣ γ ⊢² M ⊑ N ∶ p
      → Σ[ pᵖ ∈ Aₛ CTI2.⊑ᵂ⟨ Wᵖ₁ ⟩ C ]
          Wᵖ₁ CTI2.∣ γᵖ₁ ⊢² M ⊑ N ∶ pᵖ
    q₁ : Aₛ CTI2.⊑ᵂ⟨ W ⟩ B
    keep₁ : ∀ {M N N₁}
      → W CTI2.∣ γ ⊢² M ⊑ N ↑ c ∶ q₁
      → (N ↑ c) —→[ keep ] N₁
      → Value N₁
      → W CTI2.∣ γ ⊢² M ⊑ N₁ ∶ q₁

    Wᵖ₂ : CTI2.World Δᴸ (suc Δᴿ) Δ
    γᵖ₂ : CTI2.CtxImp Wᵖ₂
    X₂? : Maybe (TyVar (suc Δᴿ))
    mono₂ : CTI2.ImpEnvMono W Wᵖ₂
    rebase₂ : CTI2.RebaseAtᴿ W Wᵖ₂ X₂?
    same₂ : CTI2.SameCtx γ γᵖ₂
    targetConversion₂ : CTI2.targetStoreʷ W CTI2.⊢↑[ X₂? ]
      〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗
    transport₂ :
      ∀ {M : Term Δᴸ} {N : Term (suc Δᴿ)}
        {p : Aₛ CTI2.⊑ᵂ⟨ W ⟩ B}
      → W CTI2.∣ γ ⊢² M ⊑ N ∶ p
      → Σ[ pᵖ ∈ Aₛ CTI2.⊑ᵂ⟨ Wᵖ₂ ⟩ B ]
          Wᵖ₂ CTI2.∣ γᵖ₂ ⊢² M ⊑ N ∶ pᵖ
    q₂ : Aₛ CTI2.⊑ᵂ⟨ W ⟩
      replaceTy Fin.zero (⇑ᵗ (＇ X)) B
    keep₂ : ∀ {M N N₁}
      → W CTI2.∣ γ ⊢² M
          ⊑ N ↑ 〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗 ∶ q₂
      → (N ↑ 〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗) —→[ keep ] N₁
      → Value N₁
      → W CTI2.∣ γ ⊢² M ⊑ N₁ ∶ q₂


record StructuralConcealGeneratedFrameGeometry {Δᴸ Δᴿ Δ}
    (W : CTI2.World Δᴸ (suc Δᴿ) Δ)
    (γ : CTI2.CtxImp W)
    (Aₛ : Ty Δᴸ)
    (B C : Ty (suc Δᴿ))
    (X : TyVar Δᴿ)
    (c : Conv↓ (suc Δᴿ) C B) : Set₁ where
  field
    Wᵖ₁ : CTI2.World Δᴸ (suc Δᴿ) Δ
    γᵖ₁ : CTI2.CtxImp Wᵖ₁
    X₁? : Maybe (TyVar (suc Δᴿ))
    mono₁ : CTI2.ImpEnvMono W Wᵖ₁
    rebase₁ : CTI2.RebaseAtᴿ Wᵖ₁ W X₁?
    same₁ : CTI2.SameCtx γ γᵖ₁
    targetConversion₁ : CTI2.targetStoreʷ W CTI2.⊢↓[ X₁? ] c
    transport₁ :
      ∀ {M : Term Δᴸ} {N : Term (suc Δᴿ)}
        {p : Aₛ CTI2.⊑ᵂ⟨ W ⟩ C}
      → W CTI2.∣ γ ⊢² M ⊑ N ∶ p
      → Σ[ pᵖ ∈ Aₛ CTI2.⊑ᵂ⟨ Wᵖ₁ ⟩ C ]
          Wᵖ₁ CTI2.∣ γᵖ₁ ⊢² M ⊑ N ∶ pᵖ
    q₁ : Aₛ CTI2.⊑ᵂ⟨ W ⟩ B
    keep₁ : ∀ {M N N₁}
      → W CTI2.∣ γ ⊢² M ⊑ N ↓ c ∶ q₁
      → (N ↓ c) —→[ keep ] N₁
      → Value N₁
      → W CTI2.∣ γ ⊢² M ⊑ N₁ ∶ q₁

    Wᵖ₂ : CTI2.World Δᴸ (suc Δᴿ) Δ
    γᵖ₂ : CTI2.CtxImp Wᵖ₂
    X₂? : Maybe (TyVar (suc Δᴿ))
    mono₂ : CTI2.ImpEnvMono W Wᵖ₂
    rebase₂ : CTI2.RebaseAtᴿ W Wᵖ₂ X₂?
    same₂ : CTI2.SameCtx γ γᵖ₂
    targetConversion₂ : CTI2.targetStoreʷ W CTI2.⊢↑[ X₂? ]
      〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗
    transport₂ :
      ∀ {M : Term Δᴸ} {N : Term (suc Δᴿ)}
        {p : Aₛ CTI2.⊑ᵂ⟨ W ⟩ B}
      → W CTI2.∣ γ ⊢² M ⊑ N ∶ p
      → Σ[ pᵖ ∈ Aₛ CTI2.⊑ᵂ⟨ Wᵖ₂ ⟩ B ]
          Wᵖ₂ CTI2.∣ γᵖ₂ ⊢² M ⊑ N ∶ pᵖ
    q₂ : Aₛ CTI2.⊑ᵂ⟨ W ⟩
      replaceTy Fin.zero (⇑ᵗ (＇ X)) B
    keep₂ : ∀ {M N N₁}
      → W CTI2.∣ γ ⊢² M
          ⊑ N ↑ 〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗 ∶ q₂
      → (N ↑ 〖 Fin.zero , ⇑ᵗ (＇ X) ↑ B 〗) —→[ keep ] N₁
      → Value N₁
      → W CTI2.∣ γ ⊢² M ⊑ N₁ ∶ q₂
