module proof.PairedLambda.Terminal.NuImprecisionPairedTargetClosingStrictSpine where

-- File Charter:
--   * Aggregates the strict paired-index allocation and target-closing
--     architecture used by source `ν` and runtime `ν ★` catch-up.
--   * Provides the focused integration check for this proof family; it
--     imports strict statements, higher-order proofs, and completed canonical
--     `Lemma` assemblies without requiring a broad aggregate check.
--   * Deliberately excludes the broad simulation modules and permissive
--     scratch development.

import proof.PairedLambda.Core.NuImprecisionPairedLambdaTargetClosingRelationCounterexample
import proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameViewDef
import proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameViewProof
import proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameViewProperties
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersDef
import
  proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingPendingTargetFramesDef
import
  proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingPendingTargetMaterializationDef
import
  proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingPendingTargetMaterializationProof
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaTargetClosingNuTerminalDef
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaTargetClosingNuTerminalProof
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaTargetClosingNuTerminalLemma
import proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingAllTerminalDef
import proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingAllTerminalProof
import proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingMaterializedTerminalDef
import proof.PairedLambda.Terminal.NuImprecisionPairedLambdaTargetClosingMaterializedTerminalProof
import
  proof.PairedLambda.Continuation.ValueTerminal.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalDef
import
  proof.PairedLambda.Continuation.ValueTerminal.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalMaterializationProof
import
  proof.PairedLambda.Continuation.ValueTerminal.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalPrefixBranchDef
import
  proof.PairedLambda.Continuation.ValueTerminal.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalPrefixBranchProof
import proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationFromViewDef
import proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationFromViewProof
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationHandlersDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationProof
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationLambdaLambdaLeafDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationLambdaLeafDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationGenNuLeafDef
import
  proof.PairedLambda.Continuation.Frames.NuImprecisionPairedLambdaTargetClosingContinuationUpGenLeafDef
import
  proof.PairedLambda.Continuation.Frames.NuImprecisionPairedLambdaTargetClosingContinuationSourceGenFrameDef
import
  proof.PairedLambda.Continuation.SourceAll.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllNarrowingFrameDef
import
  proof.PairedLambda.Continuation.SourceAll.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllWideningFrameDef
import
  proof.PairedLambda.Continuation.SourceAll.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllRevealFrameDef
import
  proof.PairedLambda.Continuation.SourceAll.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllConcealFrameDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationPairedConversionFrameDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationPairedWideningFrameDef
import
  proof.PairedLambda.Continuation.Frames.NuImprecisionPairedLambdaTargetClosingContinuationUpIdFrameDef
import
  proof.PairedLambda.Continuation.Frames.NuImprecisionPairedLambdaTargetClosingContinuationUpGenAllFrameDef
import
  proof.PairedLambda.Continuation.Core.NuImprecisionPairedLambdaTargetClosingContinuationHandlersAssemblyProof
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameDef
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameCasesDef
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameProof
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetRevealCoreDef
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetRevealProof
import proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingProof
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersProof
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingCapabilitiesDef
import
  proof.PairedLambda.FrameClosing.Target.NuImprecisionPairedLambdaTargetClosingFrameClosingAssemblyProof
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingLambdaLambdaConversionRotationCounterexample
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationDef
import proof.Source.FreshTypePath.NuImprecisionFreshTypePath
import proof.Source.FreshTypePath.NuImprecisionFreshTypePathTransport
import proof.Source.FreshTypePath.NuImprecisionFreshTypePathArrowRouteDef
import proof.Source.FreshTypePath.NuImprecisionFreshTypePathImprecisionTransportDef
import proof.Source.FreshTypePath.NuImprecisionFreshTypePathImprecisionTransportProof
import proof.NuCore.Relations.NuImprecisionConversionAbsenceIdentityDef
import proof.NuCore.Relations.NuImprecisionConversionAbsenceIdentityProof
import proof.NuCore.Relations.NuImprecisionConversionAbsenceIdentityLemma
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathSquareDef
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetHalfSquareDef
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetStructuralHalfSquareDef
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetStructuralHalfSquareProof
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetStructuralHalfSquareLemma
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetHalfSquareProof
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathTargetHalfSquareLemma
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathSquareProof
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathSquareLemma
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathCycleDef
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathCycleProof
import
  proof.PairedLambda.UniversalConversion.NuImprecisionPairedUniversalConversionFreshPathCycleLemma
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationProof
import
  proof.PairedLambda.LambdaLeaves.Core.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingDef
import
  proof.PairedLambda.LambdaLeaves.Core.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingProof
import
  proof.PairedLambda.LambdaLeaves.Core.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingDef
import
  proof.PairedLambda.LambdaLeaves.Conversion.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafPairedConversionCasesDef
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralRevealClosingDef
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralAllRevealClosingDef
import
  proof.PairedLambda.LambdaLeaves.MatchedUnseal.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafMatchedUnsealClosingDef
import proof.NuCore.Misc.NuImprecisionCommonTargetExtensionCycleDef
import proof.NuCore.Misc.NuImprecisionCommonTargetExtensionCycleProof
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaClosingIndexCycleDef
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaClosingIndexCycleProof
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaClosingIndexCycleLemma
import
  proof.PairedLambda.LambdaLeaves.MatchedUnseal.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafMatchedUnsealClosingProof
import
  proof.PairedLambda.LambdaLeaves.MatchedUnseal.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafMatchedUnsealClosingLemma
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralRevealClosingProof
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralRevealClosingFromAllConversionProof
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralConcealClosingDef
import
  proof.PairedLambda.LambdaLeaves.Structural.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralConcealClosingFromAllConversionProof
import
  proof.PairedLambda.LambdaLeaves.Conversion.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafPairedConversionCasesProof
import
  proof.PairedLambda.LambdaLeaves.Core.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingProof
import proof.NuCore.Relations.NuImprecisionCorrespondingSourceNameNotStarDef
import proof.NuCore.Relations.NuImprecisionCorrespondingSourceNameNotStarProof
import proof.NuCore.Relations.NuImprecisionCorrespondingSourceNameNotStarLemma
import proof.NuCore.Relations.NuImprecisionMatchedLiftInvariantsDef
import proof.NuCore.Relations.NuImprecisionMatchedLiftInvariantsProof
import proof.NuCore.Relations.NuImprecisionMatchedLiftInvariantsLemma
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenLeafAllIndexClosingDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingProof
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationProof
import proof.PairedLambda.LambdaLeaves.NuLeaf.NuImprecisionPairedLambdaTargetClosingGenLeafNuClosingProof
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationDef
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFramePairedConversionCasesDef
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingDef
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingCoreDef
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingProof
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralConcealClosingDef
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFramePairedConversionCasesProof
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationProof
import
  proof.PairedLambda.SourceFrames.SourceGen.NuImprecisionPairedLambdaTargetClosingSourceGenFrameClosingProof
import
  proof.PairedLambda.SourceFrames.SourceAll.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationDef
import
  proof.PairedLambda.SourceFrames.SourceAll.NuImprecisionPairedLambdaTargetClosingSourceAllFrameAllIndexClosingDef
import
  proof.PairedLambda.SourceFrames.SourceAll.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationProof
import
  proof.PairedLambda.SourceFrames.SourceAll.NuImprecisionPairedLambdaTargetClosingSourceAllFrameClosingProof
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedConversionFramePairedConversionCasesDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingProof
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleCasesDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleSourceInertCoreDef
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleSourceInertProof
import
  proof.PairedLambda.Conversions.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingProof
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpIdFrameWideningCasesDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingProof
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameWideningCasesDef
import
  proof.PairedLambda.SourceFrames.UpFrames.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingProof
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationDef
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewProof
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationFrameClosingDef
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationProof
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAssemblyProof
import
  proof.Source.NuPaired.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewDef
import proof.NuCore.Misc.NuImprecisionPairedStorePrefixFactorDef
import proof.NuCore.Misc.NuImprecisionPairedStorePrefixFactorProof
import proof.NuCore.Misc.NuImprecisionPairedStorePrefixFactorLemma
import proof.Source.NuPaired.NuImprecisionSourceNuPairedBinderSupport
import proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupDef
import proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupProof
import
  proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexViewCatchupDef
import proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupDef
import proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupProof
import proof.WorldCoherent.Final.SourceNu.NuImprecisionWorldCoherentFinalSourceNuPairedIndexViewCatchupDef
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentLeftCatchupPrependKeepStep
import
  proof.WorldCoherent.PairedLambda.AllReveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupDef
import
  proof.WorldCoherent.PairedLambda.AllReveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupProof
import
  proof.WorldCoherent.PairedLambda.AllReveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationDef
import
  proof.WorldCoherent.PairedLambda.AllReveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationProof
import
  proof.WorldCoherent.PairedLambda.AllReveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationSourceViewDef
import
  proof.WorldCoherent.PairedLambda.AllWiden.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupDef
import
  proof.WorldCoherent.PairedLambda.AllWiden.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupProof
import
  proof.WorldCoherent.PairedLambda.AllWiden.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupSourceViewDef
import
  proof.WorldCoherent.PairedLambda.Instantiation.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstPostBetaCatchupDef
import
  proof.WorldCoherent.PairedLambda.Instantiation.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupDef
import
  proof.WorldCoherent.PairedLambda.Instantiation.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupProof
import proof.WorldCoherent.PairedLambda.Reveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupDef
import
  proof.WorldCoherent.PairedLambda.Reveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupProof
import proof.WorldCoherent.PairedLambda.Reveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupDef
import
  proof.WorldCoherent.PairedLambda.Reveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupProof
import
  proof.WorldCoherent.PairedLambda.Reveal.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealSpineWidenCatchupDef
import proof.WorldCoherent.PairedLambda.Core.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupDef
import
  proof.WorldCoherent.PairedLambda.Core.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupProof
import
  proof.WorldCoherent.Source.NuCatchup.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuCatchup.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupProof
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupProof
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupAssemblyProof
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaUnsealClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupProof
import proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupProof
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupAssemblyProof
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedAllWideningTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupDef
import
  proof.WorldCoherent.Source.NuPaired.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupProof
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentTargetInertFrameCatchupDef
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentTargetInertFrameCatchupProof
