module proof.DGG.WorldInvariants where

-- File Charter:
--   * Exposes the live structural world invariants at a world-indexed
--     theorem surface.
--   * Derives target non-occupancy and the conceal see-through premise
--     directly from the invariants generated by CtxImp.World.
--   * Contains no independent world representation or invariant companion.

open import Data.Empty using (⊥)
open import Data.Maybe using (just; nothing)
open import Data.Product using (_,_)
open import Relation.Binary.PropositionalEquality using (_≡_)

open import Types
open import TyStore using (lookupStore; lookupStore-∋)
open import Consistency using (toRenameᵗ)
open import Conversion using (seal)
import Conversion as Conv
open import Imprecision using (X⊑★)
import proof.DGG.CtxImp as CTX

WorldInvariants : ∀ {Δᴸ Δᴿ Δ}
  → CTX.World Δᴸ Δᴿ Δ
  → Set
WorldInvariants W =
  CTX.WorldInvariants
    (CTX.ηᴸʷ W) (CTX.ηᴿʷ W) (CTX.impEnvʷ W)
    (CTX.sourceStoreʷ W) (CTX.targetStoreʷ W)

world-invariants : ∀ {Δᴸ Δᴿ Δ}
  → (W : CTX.World Δᴸ Δᴿ Δ)
  → WorldInvariants W
world-invariants = CTX.invariantsʷ

world-invariants-no-target-at-dynamic-star : ∀ {Δᴸ Δᴿ Δ}
    {W : CTX.World Δᴸ Δᴿ Δ} {X : TyVar Δᴸ}
  → WorldInvariants W
  → CTX.impEnvʷ W (toRenameᵗ (CTX.ηᴸʷ W) X) ≡ X⊑★
  → lookupStore (CTX.sourceStoreʷ W) X ≡ ★
  → CTX.NoTargetOccupantAtSource W X
world-invariants-no-target-at-dynamic-star {X = X} inv mark entry
    (Xᴿ , aligned) =
  CTX.dynamicStarSourcesUnoccupied inv X mark entry Xᴿ aligned

world-invariants-see-through-premise : ∀ {Δᴸ Δᴿ Δ}
    {W W′ : CTX.World Δᴸ Δᴿ Δ} {X : TyVar Δᴸ}
  → WorldInvariants W′
  → CTX.TagRebaseAtᴸ W′ W (just X) nothing
  → CTX.sourceStoreʷ W Conv.⊢↓[ just X ] seal X ★
  → CTX.NoTargetOccupantAtSource W′ X
world-invariants-see-through-premise {W′ = W′} {X = X} inv
    (CTX.tag-rebase-onlyᴸ mark disaligned represented)
    (Conv.⊢↓-sealˣ source∋) =
  world-invariants-no-target-at-dynamic-star {W = W′} {X = X} inv mark
    (lookupStore-∋ source∋)

world-invariants-d17c-occupancy : ∀ {Δᴸ Δᴿ Δ}
    {W : CTX.World Δᴸ Δᴿ Δ} {X : TyVar Δᴸ}
  → WorldInvariants W
  → CTX.impEnvʷ W (toRenameᵗ (CTX.ηᴸʷ W) X) ≡ X⊑★
  → lookupStore (CTX.sourceStoreʷ W) X ≡ ★
  → CTX.Occupied W (toRenameᵗ (CTX.ηᴸʷ W) X)
  → ⊥
world-invariants-d17c-occupancy {W = W} {X = X} inv mark entry =
  world-invariants-no-target-at-dynamic-star {W = W} {X = X}
    inv mark entry
