M5 relational blocker: `Λ-cont`

Date: 2026-08-11

Blocked statement:

  InstRelContinuationSurface.Λ-cont

This is the `allv-Λ` branch of `InstCatchupRightAt fuel`, after the common
`β-inst` prefix and the catalogued `β-Λ` target step.

The direct proof gets stuck at the post-catalog relation:

  W₂ ∣ γ₂ ⊢² M ⊑ (V′₂ ↑ 〖 Fin.zero , ★ ↑ B 〗) ∶ p₂

where `W₂` is the two-step right extension generated by `bind ★` and the
catalog allocation for the fresh instantiation variable, and `p₂` is the
source obligation needed as the source side of the residual cast
`χ ▷ᶜ ↑ᶜ (close-instᶜ c′)`.

The available premises are only:

  W ∣ γ ⊢² M ⊑ M′ ∶ p
  Value M
  Value M′
  M′ ≡ Λ V′

There is no live stage-1 inversion surface that turns a relation against a
target `Λ` value into the source-side `Λ⊑²` continuation needed after the
target type application.  Pattern matching on `_∣_⊢²_⊑_∶_` would have
to rebuild through source casts/reveals/conceals and transport the body
relation across the right-only allocation worlds; that package is not
present.

The residual provenance subgoal is also not derivable from the available
premises:

  CatchupCast⁻ p₂ (χ ▷ᶜ ↑ᶜ (close-instᶜ c′))
    (ECR.transport⊑ᵂ ext₂ q)

The smallest live surface change made in this pass is the new
`InstRelContinuationSurface` record in
`Catchup/InstCatchupRightRelDef.agda`, with `Λ-cont` carrying this exact
per-view continuation as an explicit obligation.  A real proof needs a
target-`Λ` relational inversion/continuation package that returns both the
post-catalog relation and the residual `CatchupCast⁻`.
