# NS-4 stage 1s resister: strict child relation for target wrappers

Date: 2026-08-15

Status: open.

What closed in live Agda:

The opened cast generated by an `∀ᶜ` target frame is no longer a residual
stop.  `opened-all-cast-frame-class` derives:

```agda
CastFrameClass (d [ ＇ X ]ᶜ)
```

from the strict mark equation, `NonVar C`, and `zero ∈ᵗ C`, then dispatches
through `GenSafeView`.  The cases are only:

- `cast-inert inert`, for generated safe casts classified as inert;
- `cast-safe (safe-inst B≢★)`, for the exact instantiation-safe case.

No `catchup⁻-∀-open` constructor was added, and no residual provenance is
invented for the opened cast.


New resister
------------

The next assembly failure is the relation side of the strict target-head
cells, not the opened-cast classifier.

For the concrete `allv-∀` branch, the parent strict surface has:

```agda
rel : W ∣ γ ⊢² M ⊑ V ⟨ ∀ᶜ d ⟩ ∶ p
p   : Aₛ ⊑ᵂ⟨ W ⟩ `∀ C
```

`structural-target-all-peel` and `opened-all-cast-frame-class` provide the
target child package and typed child spine:

```agda
StructuralTargetInstantiationPackage W V
  (name-type-app-frame B X refl refl ▻ⁱ
   cast-frame (d [ ＇ X ]ᶜ) ▻ⁱ
   mapInstantiationSpine keep spine)
```

But the recursive structural child also needs:

```agda
child-relation : W ∣ γ ⊢² M ⊑ V ∶ child-endpoint
child-endpoint : Aₛ ⊑ᵂ⟨ W ⟩ `∀ B
```

No live surface currently derives that child relation from the parent relation
against `V ⟨ ∀ᶜ d ⟩`.

The existing frame-absorption helper has the opposite direction:

```agda
target-frame-cast-absorption :
  W ∣ γ ⊢² M ⊑ V ∶ p →
  W ∣ γ ⊢² M ⊑ V ⟨ c ⟩ ∶ q
```

and `FuelStepSurface.smaller-extra` also consumes an already-peeled relation
to the uncast target before normalizing an extra target cast.  Neither can
invert the available parent derivation.

The same relation-side gap appears in the other strict target-wrapper cells:

- `allv-gen` peels the target package to `⇑ᵗᵐ V` under the generated
  cast/reveal/transport spine, but the parent relation is against
  `V ⟨ gen c ⟩`.
- `allv-reveal` peels the target package to `⇑ᵗᵐ V`, but the parent relation
  is against:

  ```agda
  V ↑ `∀↑ c
  ```

- `allv-conceal` peels the target package to `⇑ᵗᵐ V`, but the parent relation
  is against:

  ```agda
  V ↓ `∀↓ c
  ```

Target extension can lift an inner relation after allocation; the missing
piece is obtaining that inner relation in the first place.


Consequence
-----------

Stop on the strict-child relation surface.  The `∀` opened-cast classifier is
available and the target-only peels are available, but the strict view cells
cannot be inhabited until there is a relation inversion/discharge surface for
target wrappers, or the strict-cell statements are intentionally redesigned to
carry that relation evidence.

This is independent of the older public value adapter blocker from
`ns4-stage-1o-target-builder-resister.red`: `StructuralValueInstantiationᵀ`
still lacks a caller-supplied root target package or a total target normalizer.


SUPERVISOR CORRECTION postscript, 2026-08-15
--------------------------------------------

The strict-child relation gaps named above are not stage-1 obligations.
They are intentionally deferred to the higher-order strict view surface
inhabitants:

- `StructuralΛStrictSurfaceᵀ`
- `StructuralAllCastStrictSurfaceᵀ`
- `StructuralGenStrictSurfaceᵀ`
- `StructuralRevealStrictSurfaceᵀ`
- `StructuralConcealStrictSurfaceᵀ`

Those inhabitants are NS-4 stage 2 producers and are expected to use the
M3-style target-wrapper inversion machinery.  Stage 1 only delegates to these
surfaces and consumes their returned `StructuralStrictChild` data.

The deferred square for each strict target wrapper has the same shape:

$$
\begin{array}{ccc}
M & \sqsubseteq & \operatorname{wrap}(V) \\
\downarrow^{0} & & \downarrow \\
M & \sqsubseteq & V_{\mathsf{child}}
\end{array}
$$

Precision is horizontal and reduction is vertical.  The bottom horizontal
edge is supplied by the corresponding strict surface inhabitant, not by the
stage-1 structural worker.
