SourceStripWorkerProof attempt 2 blocked at source-spine dispatch scale.

Command:

  AGDA_DIR=/tmp/claude-26597/-home-runner-AI-for-pl/abaf167a-fb69-4f9e-bdf7-5f069c5047b5/scratchpad/agda-home agda -i GTSFImp -v0 GTSFImp/proof/DGG/Inversion/SourceStripWorkerProof.agda

Current state:

* The original two star-rep/name-protected source-seal cases against a tagged
  sealed target have concrete proof terms in SourceStripWorkerProof.agda.
* The target tag is destructed through the `⊑cast²` premise and the exposed
  untagged sealed-target premise is repackaged through
  `source-cast-seal-final`, `source-seal-cast-final`,
  `source-seal-final`, and the corresponding branch helpers.
* Helper-only probe, generated by cutting SourceStripWorkerProof.agda just
  before `source-spine-strip-worker`, checks in about 4 seconds.
* A source-spine-only probe, generated by cutting before
  `source-column-strip-worker-D`, does not finish within 900 seconds.
* The full SourceStripWorkerProof.agda does not finish within 420 seconds.

Concrete reduction/imprecision square for the blocked source-cast-over-seal
case:

$$
\begin{array}{ccc}
((V \downarrow \mathsf{seal}\ X\ R_i)\langle c\rangle)
  \downarrow \mathsf{seal}\ X_L\ \star
& \sqsubseteq &
U \downarrow \mathsf{seal}\ Y\ S
\\
\downarrow^{*} & & \downarrow^{*}
\\
\mathsf{strip}(V, X, R_i, c, X_L)
& \sqsubseteq &
\mathsf{strip}(U, Y, S)
\end{array}
$$

The exposed premise used by the branch is:

$$
W_i \mid \gamma_i \vdash^2
  V \sqsubseteq U \downarrow \mathsf{seal}\ Y\ S
  : R_i \sqsubseteq_{W_i} \mathsf{`var}\ Y
$$

Concrete reduction/imprecision square for the blocked source-seal case:

$$
\begin{array}{ccc}
(V \downarrow \mathsf{seal}\ X\ R_i)
  \downarrow \mathsf{seal}\ X_L\ \mathsf{`var}\ X
& \sqsubseteq &
U \downarrow \mathsf{seal}\ Y\ S
\\
\downarrow^{*} & & \downarrow^{*}
\\
\mathsf{strip}(V, X, R_i, X_L)
& \sqsubseteq &
\mathsf{strip}(U, Y, S)
\end{array}
$$

The exposed premise used by the branch is:

$$
W_i \mid \gamma_i \vdash^2
  V \sqsubseteq U \downarrow \mathsf{seal}\ Y\ S
  : R_i \sqsubseteq_{W_i} \mathsf{`var}\ Y
$$

Likely next step:

Split `source-spine-strip-worker` structurally instead of adding more RHS
helpers. The branch helper bodies are fast in isolation; the remaining
blocker is Agda processing the whole monolithic source-spine clause set.
The promising split is:

* top-level `source-spine-strip-worker` dispatches only on coarse
  `SpineValue` form;
* source-cast-over-seal, source-seal-cast, and source-seal cases move into
  smaller D-first helper functions;
* the top-level worker keeps only one broad clause per coarse source spine
  shape, so Agda does not compare every large indexed left-hand side in one
  clause set.
