module proof.PreservationBetaLambda where

-- File Charter:
--   * Worker proof file for the store-allocating PolyConvert β-Λ redex.
--   * Proves the fresh-seal conversion generated by `convert↑`.
--   * Exports `preserve-β-Λ`, matching the obligation in `proof/Preservation`.

open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.Empty using (⊥-elim)
open import Data.List using (List; []; _∷_; _++_; length; map)
open import Data.Nat using (zero; suc; z<s; s<s; _<_)
open import Data.Nat.Properties using (≤-refl; n≤1+n; n<1+n; _≟_)
open import Data.Product using (_,_)
open import Relation.Nullary using (yes; no)
open import Relation.Binary.PropositionalEquality
  using (_≢_; cong; cong₂; refl; subst; sym; trans)

open import Types
open import proof.TypeProperties
  using
    ( WfTy-weakenˢ
    ; TySubstWf-exts
    ; singleTyEnv-Wf
    ; substᵗ-preserves-WfTy
    ; substᵗ-substᵗ
    )
open import Ctx using (⤊ᵗ; map-substᵗ-⤊ᵗ; substLookup)
open import Store
open import Imprecision
  using
    ( Imp
    ; ICtx
    ; VarMode
    ; _∣_⊢_⦂_⊑_
    ; plain
    ; plains
    ; starImp
    ; substImp
    ; substPlainAtImp
    )
open import Conversion
open import Terms
open import proof.PreservationBetaDownForall
  using (open-fresh-∀⊑-prefix; substWf-plain-prefix)
open import proof.PreservationBetaRevealConceal
  using (subst↑-wt; subst↓-wt)
open import proof.PreservationWkConv using (wk-conv↑; wk-conv↓)
open import proof.PreservationWkTerm using (wk-term)

------------------------------------------------------------------------
-- Fresh type-variable opening for terms
------------------------------------------------------------------------

substᵗ-[]ᵗ :
  (σ : Substᵗ) (A T : Ty) →
  substᵗ σ (A [ T ]ᵗ) ≡ (substᵗ (extsᵗ σ) A) [ substᵗ σ T ]ᵗ
substᵗ-[]ᵗ σ A T =
  trans
    (substᵗ-substᵗ σ (singleTyEnv T) A)
    (trans
      (substᵗ-cong env A)
      (sym (substᵗ-substᵗ (singleTyEnv (substᵗ σ T)) (extsᵗ σ) A)))
  where
    env :
      (X : TyVar) →
      substᵗ σ (singleTyEnv T X) ≡
      substᵗ (singleTyEnv (substᵗ σ T)) (extsᵗ σ X)
    env zero = refl
    env (suc X) = sym (open-renᵗ-suc (σ X) (substᵗ σ T))

substᵗ-constTy : (σ : Substᵗ) (κ : Const) →
  substᵗ σ (constTy κ) ≡ constTy κ
substᵗ-constTy σ (κℕ n) = refl

map-singleTyEnv-⤊ᵗ :
  (T : Ty) (Γ : Ctx) →
  map (substᵗ (singleTyEnv T)) (⤊ᵗ Γ) ≡ Γ
map-singleTyEnv-⤊ᵗ T [] = refl
map-singleTyEnv-⤊ᵗ T (A ∷ Γ) =
  cong₂ _∷_ (open-renᵗ-suc A T) (map-singleTyEnv-⤊ᵗ T Γ)

cong-⊢Δ⦂ :
  ∀ {Δ Δ′ Ψ}{Σ : Store}{Γ : Ctx}{M : Term}{A : Ty} →
  Δ ≡ Δ′ →
  Δ ∣ Ψ ∣ Σ ∣ Γ ⊢ M ⦂ A →
  Δ′ ∣ Ψ ∣ Σ ∣ Γ ⊢ M ⦂ A
cong-⊢Δ⦂ refl M⊢ = M⊢

plainSubst-star-up :
  ∀ k α X →
  UpValue (starImp (plainSubstVarFrom k (｀ α) X))
plainSubst-star-up zero α zero = tag
plainSubst-star-up zero α (suc X) = tagν
plainSubst-star-up (suc k) α zero = tagν
plainSubst-star-up (suc k) α (suc X)
  with plainSubstVarFrom k (｀ α) X | plainSubst-star-up k α X
... | ＇ Y | tagν = tagν
... | ｀ β | tag = tag
... | ‵ ι | tag = tag
... | A ⇒ B | tag = tag

mutual
  substPlain-up-value :
    ∀ {p} k α →
    UpValue p →
    UpValue (substImp (plainSubstVarFrom k (｀ α)) p)
  substPlain-up-value k α (tagν {X = X}) = plainSubst-star-up k α X
  substPlain-up-value k α tag = tag
  substPlain-up-value k α (_↦_ {p = p} {q = q}) = _↦_
  substPlain-up-value k α (`∀ {p = p}) = `∀

  substPlain-down-value :
    ∀ {p} k α →
    DownValue p →
    DownValue (substImp (plainSubstVarFrom k (｀ α)) p)
  substPlain-down-value k α (_↦_ {p = p} {q = q}) = _↦_
  substPlain-down-value k α (`∀ {p = p}) = `∀
  substPlain-down-value k α (ν_ {B = B} {p = p}) =
    ν_ {B = substᵗ (plainSubstVarFrom k (｀ α)) B}
      {p = substImp (plainSubstVarFrom (suc k) (｀ α)) p}

mutual
  substPlain-reveal-value :
    ∀ {c} k α →
    RevealValue c →
    RevealValue (subst↑ (plainSubstVarFrom k (｀ α)) c)
  substPlain-reveal-value k α (_↦_ {p = p} {q = q}) = _↦_
  substPlain-reveal-value k α (`∀ {c = c}) = `∀

  substPlain-conceal-value :
    ∀ {c} k α →
    ConcealValue c →
    ConcealValue (subst↓ (plainSubstVarFrom k (｀ α)) c)
  substPlain-conceal-value k α seal = seal
  substPlain-conceal-value k α (_↦_ {p = p} {q = q}) = _↦_
  substPlain-conceal-value k α (`∀ {c = c}) = `∀

substPlain-value :
  ∀ {V} k α →
  Value V →
  Value (substᵗᵐ (plainSubstVarFrom k (｀ α)) V)
substPlain-value k α (ƛ A ⇒ N) =
  ƛ substᵗ (plainSubstVarFrom k (｀ α)) A ⇒
    substᵗᵐ (plainSubstVarFrom k (｀ α)) N
substPlain-value k α ($ κ) = $ κ
substPlain-value k α (Λ N) =
  Λ substᵗᵐ (plainSubstVarFrom (suc k) (｀ α)) N
substPlain-value k α (vV ⇑ p) =
  substPlain-value k α vV ⇑ substPlain-up-value k α p
substPlain-value k α (vV ⇓ p) =
  substPlain-value k α vV ⇓ substPlain-down-value k α p
substPlain-value k α (vV ↑ c) =
  substPlain-value k α vV ↑ substPlain-reveal-value k α c
substPlain-value k α (vV ↓ c) =
  substPlain-value k α vV ↓ substPlain-conceal-value k α c

data PlainList : ICtx → Set where
  plain[] : PlainList []
  plain∷_ : ∀ {Φ} → PlainList Φ → PlainList (plain ∷ Φ)

length-plains : ∀ Δ → length (plains Δ []) ≡ Δ
length-plains zero = refl
length-plains (suc Δ) = cong suc (length-plains Δ)

PlainList-plains :
  ∀ {Φ} →
  PlainList Φ →
  (Δ : TyCtx) →
  plains (length (Φ ++ plains Δ [])) [] ≡ Φ ++ plains Δ []
PlainList-plains plain[] Δ rewrite length-plains Δ = refl
PlainList-plains (plain∷ plainΦ) Δ =
  cong (plain ∷_) (PlainList-plains plainΦ Δ)

open-fresh-∀⊑-plains :
  ∀ {Δ Ψ}{Σ : Store}{Φ : ICtx}{A B : Ty}{p : Imp} →
  PlainList Φ →
  StoreWf Δ Ψ Σ →
  _∣_⊢_⦂_⊑_
    Ψ
    (plains (length (Φ ++ plain ∷ plains Δ [])) [])
    p A B →
  _∣_⊢_⦂_⊑_
    (suc Ψ)
    (plains (length (Φ ++ plains Δ [])) [])
    (substPlainAtImp (length Φ) (｀ (length Σ)) p)
    (substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) A)
    (substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) B)
open-fresh-∀⊑-plains
  {Δ = Δ} {Ψ = Ψ} {Σ = Σ} {Φ = Φ} {A = A} {B = B} {p = p}
  plainΦ wfΣ p⊢ =
  subst
    (λ Γ →
      _∣_⊢_⦂_⊑_
        (suc Ψ)
        Γ
        (substPlainAtImp (length Φ) (｀ (length Σ)) p)
        (substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) A)
        (substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) B))
    (sym (PlainList-plains plainΦ Δ))
    (open-fresh-∀⊑-prefix {Φ = Φ} wfΣ
      (subst
        (λ Γ → _∣_⊢_⦂_⊑_ Ψ Γ p A B)
        (PlainList-plains plainΦ (suc Δ))
        p⊢))

openTerm-fresh-∀-prefix :
  ∀ {Δ Ψ}{Σ Σ₀ : Store}{Φ : ICtx}{Γ : Ctx}{M : Term}{A : Ty} →
  PlainList Φ →
  StoreWf Δ Ψ Σ →
  length (Φ ++ plain ∷ plains Δ []) ∣ Ψ ∣ Σ₀ ∣ Γ ⊢ M ⦂ A →
  length (Φ ++ plains Δ []) ∣ suc Ψ ∣
    substStoreᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) Σ₀ ∣
    map (substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ)))) Γ ⊢
    substᵗᵐ (plainSubstVarFrom (length Φ) (｀ (length Σ))) M ⦂
    substᵗ (plainSubstVarFrom (length Φ) (｀ (length Σ))) A
openTerm-fresh-∀-prefix plainΦ wfΣ (⊢` h) = ⊢` (substLookup _ h)
openTerm-fresh-∀-prefix {Φ = Φ} plainΦ wfΣ (⊢ƛ wfA M⊢) =
  ⊢ƛ
    (substᵗ-preserves-WfTy
      (WfTy-weakenˢ wfA (n≤1+n _))
      (substWf-plain-prefix {Φ = Φ} wfΣ))
    (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix plainΦ wfΣ (⊢· L⊢ M⊢) =
  ⊢· (openTerm-fresh-∀-prefix plainΦ wfΣ L⊢)
     (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix {Σ = Σ} {Σ₀ = Σ₀} {Φ = Φ} {Γ = Γ} plainΦ wfΣ
  (⊢Λ {A = A} vM M⊢) =
  ⊢Λ
    (substPlain-value (suc (length Φ)) (length Σ) vM)
    (cong-⊢⦂
      (substStoreᵗ-ext-⟰ᵗ
        (plainSubstVarFrom (length Φ) (｀ (length Σ)))
        Σ₀)
      (map-substᵗ-⤊ᵗ
        (plainSubstVarFrom (length Φ) (｀ (length Σ)))
        Γ)
      refl
      refl
      (openTerm-fresh-∀-prefix {Φ = plain ∷ Φ} (plain∷ plainΦ) wfΣ M⊢))
openTerm-fresh-∀-prefix {Φ = Φ} plainΦ wfΣ
  (⊢• {B = B} {T = T} M⊢ wfB wfT) =
  cong-⊢⦂
    refl
    refl
    refl
    (sym (substᵗ-[]ᵗ (plainSubstVarFrom (length Φ) (｀ _)) B T))
    (⊢•
      (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
      (substᵗ-preserves-WfTy
        (WfTy-weakenˢ wfB (n≤1+n _))
        (TySubstWf-exts (substWf-plain-prefix {Φ = Φ} wfΣ)))
      (substᵗ-preserves-WfTy
        (WfTy-weakenˢ wfT (n≤1+n _))
        (substWf-plain-prefix {Φ = Φ} wfΣ)))
openTerm-fresh-∀-prefix plainΦ wfΣ (⊢$ κ) =
  cong-⊢⦂ refl refl refl (sym (substᵗ-constTy _ κ)) (⊢$ κ)
openTerm-fresh-∀-prefix plainΦ wfΣ (⊢⊕ L⊢ op M⊢) =
  ⊢⊕ (openTerm-fresh-∀-prefix plainΦ wfΣ L⊢) op
      (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix {Φ = Φ} plainΦ wfΣ (⊢up {p = p} p⊢ M⊢) =
  ⊢up
    (open-fresh-∀⊑-plains {Φ = Φ} plainΦ wfΣ p⊢)
    (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix {Φ = Φ} plainΦ wfΣ (⊢down {p = p} p⊢ M⊢) =
  ⊢down
    (open-fresh-∀⊑-plains {Φ = Φ} plainΦ wfΣ p⊢)
    (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix {Σ = Σ} {Σ₀ = Σ₀} {Φ = Φ} plainΦ wfΣ
  (⊢reveal c⊢ M⊢) =
  ⊢reveal
    (subst↑-wt
      (substWf-plain-prefix {Φ = Φ} wfΣ)
      (wk-conv↑ {Ψ′ = suc _} (n≤1+n _) ⊆ˢ-refl c⊢))
    (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix {Φ = Φ} plainΦ wfΣ (⊢conceal c⊢ M⊢) =
  ⊢conceal
    (subst↓-wt
      (substWf-plain-prefix {Φ = Φ} wfΣ)
      (wk-conv↓ {Ψ′ = suc _} (n≤1+n _) ⊆ˢ-refl c⊢))
    (openTerm-fresh-∀-prefix plainΦ wfΣ M⊢)
openTerm-fresh-∀-prefix plainΦ wfΣ (⊢blame ℓ) = ⊢blame ℓ

[]ᵀ-fresh-∀-wt :
  ∀ {Δ Ψ}{Σ : Store}{Γ : Ctx}{M : Term}{A : Ty} →
  StoreWf Δ Ψ Σ →
  suc Δ ∣ Ψ ∣ ⟰ᵗ Σ ∣ ⤊ᵗ Γ ⊢ M ⦂ A →
  Δ ∣ suc Ψ ∣ Σ ∣ Γ ⊢ M [ ｀ (length Σ) ]ᵀ ⦂ A [ ｀ (length Σ) ]ᵗ
[]ᵀ-fresh-∀-wt {Δ = Δ} {Σ = Σ} {Γ = Γ} wfΣ M⊢ =
  cong-⊢Δ⦂ (length-plains Δ)
    (cong-⊢⦂
      (substStoreᵗ-singleTyEnv-⟰ᵗ (｀ (length Σ)) Σ)
      (map-singleTyEnv-⤊ᵗ (｀ (length Σ)) Γ)
      refl
      refl
      (openTerm-fresh-∀-prefix {Δ = Δ} {Φ = []} plain[] wfΣ
        (cong-⊢Δ⦂ (sym (length-plains (suc Δ))) M⊢)))

------------------------------------------------------------------------
-- Fresh seal facts
------------------------------------------------------------------------

len<suc-StoreWf :
  ∀ {Δ Ψ}{Σ : Store} →
  StoreWf Δ Ψ Σ →
  length Σ < suc Ψ
len<suc-StoreWf {Ψ = Ψ} wfΣ rewrite storeWf-length wfΣ = n<1+n Ψ

------------------------------------------------------------------------
-- Conversion generated by fresh type instantiation
------------------------------------------------------------------------

cong-⊢↑ :
  ∀ {Δ Ψ}{Σ Σ′ : Store}{c c′ : Conv↑}{A A′ B B′ : Ty} →
  Σ ≡ Σ′ →
  c ≡ c′ →
  A ≡ A′ →
  B ≡ B′ →
  Δ ∣ Ψ ∣ Σ ⊢ c ⦂ A ↑ˢ B →
  Δ ∣ Ψ ∣ Σ′ ⊢ c′ ⦂ A′ ↑ˢ B′
cong-⊢↑ refl refl refl refl c⊢ = c⊢

cong-⊢↓ :
  ∀ {Δ Ψ}{Σ Σ′ : Store}{c c′ : Conv↓}{A A′ B B′ : Ty} →
  Σ ≡ Σ′ →
  c ≡ c′ →
  A ≡ A′ →
  B ≡ B′ →
  Δ ∣ Ψ ∣ Σ ⊢ c ⦂ A ↓ˢ B →
  Δ ∣ Ψ ∣ Σ′ ⊢ c′ ⦂ A′ ↓ˢ B′
cong-⊢↓ refl refl refl refl c⊢ = c⊢

plainSubstVarFrom-neq :
  ∀ X Y S₁ T →
  X ≢ Y →
  plainSubstVarFrom X S₁ Y ≡ plainSubstVarFrom X T Y
plainSubstVarFrom-neq zero zero S₁ T X≢Y = ⊥-elim (X≢Y refl)
plainSubstVarFrom-neq zero (suc Y) S₁ T X≢Y = refl
plainSubstVarFrom-neq (suc X) zero S₁ T X≢Y = refl
plainSubstVarFrom-neq (suc X) (suc Y) S₁ T X≢Y =
  cong (renameᵗ suc)
    (plainSubstVarFrom-neq X Y S₁ T (λ X≡Y → X≢Y (cong suc X≡Y)))

plainSubstVarFrom-seal-self :
  ∀ X α →
  plainSubstVarFrom X (｀ α) X ≡ ｀ α
plainSubstVarFrom-seal-self zero α = refl
plainSubstVarFrom-seal-self (suc X) α
  rewrite plainSubstVarFrom-seal-self X α = refl

mutual
  convert↑At-wt :
    ∀ {Δ Ψ}{Σ : Store}{α : Seal}{T B : Ty} →
    (Xᵛ : TyVar) →
    Σ ∋ˢ α ⦂ plainSubstVarFrom Xᵛ T Xᵛ →
    WfTy Δ Ψ (substᵗ (plainSubstVarFrom Xᵛ (｀ α)) B) →
    Δ ∣ Ψ ∣ Σ ⊢ convert↑At Xᵛ B α ⦂
      substᵗ (plainSubstVarFrom Xᵛ (｀ α)) B ↑ˢ
      substᵗ (plainSubstVarFrom Xᵛ T) B
  convert↑At-wt {α = α} {B = ＇ Y} X hα wfSrc with X ≟ Y
  convert↑At-wt {α = α} {B = ＇ .X} X hα wfSrc | yes refl =
    cong-⊢↑ refl refl (sym (plainSubstVarFrom-seal-self X α)) refl
      (⊢↑-unseal hα)
  convert↑At-wt {α = α} {T = T} {B = ＇ Y} X hα wfSrc | no X≢Y =
    cong-⊢↑ refl refl refl (plainSubstVarFrom-neq X Y (｀ α) T X≢Y)
      (⊢↑-id wfSrc)
  convert↑At-wt {B = ｀ β} X hα wfSrc = ⊢↑-id wfSrc
  convert↑At-wt {B = ‵ ι} X hα wfSrc = ⊢↑-id wfSrc
  convert↑At-wt {B = ★} X hα wfSrc = ⊢↑-id wfSrc
  convert↑At-wt {B = A ⇒ B} X hα (wf⇒ wfA wfB) =
    ⊢↑-⇒ (convert↓At-wt {B = A} X hα wfA)
          (convert↑At-wt {B = B} X hα wfB)
  convert↑At-wt {B = `∀ A} X hα (wf∀ wfA) =
    ⊢↑-∀ (convert↑At-wt {B = A} (suc X) (renameLookupᵗ suc hα) wfA)

  convert↓At-wt :
    ∀ {Δ Ψ}{Σ : Store}{α : Seal}{T B : Ty} →
    (Xᵛ : TyVar) →
    Σ ∋ˢ α ⦂ plainSubstVarFrom Xᵛ T Xᵛ →
    WfTy Δ Ψ (substᵗ (plainSubstVarFrom Xᵛ (｀ α)) B) →
    Δ ∣ Ψ ∣ Σ ⊢ convert↓At Xᵛ B α ⦂
      substᵗ (plainSubstVarFrom Xᵛ T) B ↓ˢ
      substᵗ (plainSubstVarFrom Xᵛ (｀ α)) B
  convert↓At-wt {α = α} {B = ＇ Y} X hα wfSrc with X ≟ Y
  convert↓At-wt {α = α} {B = ＇ .X} X hα wfSrc | yes refl =
    cong-⊢↓ refl refl refl (sym (plainSubstVarFrom-seal-self X α))
      (⊢↓-seal hα)
  convert↓At-wt {α = α} {T = T} {B = ＇ Y} X hα wfSrc | no X≢Y =
    cong-⊢↓ refl refl (plainSubstVarFrom-neq X Y (｀ α) T X≢Y) refl
      (⊢↓-id wfSrc)
  convert↓At-wt {B = ｀ β} X hα wfSrc = ⊢↓-id wfSrc
  convert↓At-wt {B = ‵ ι} X hα wfSrc = ⊢↓-id wfSrc
  convert↓At-wt {B = ★} X hα wfSrc = ⊢↓-id wfSrc
  convert↓At-wt {B = A ⇒ B} X hα (wf⇒ wfA wfB) =
    ⊢↓-⇒ (convert↑At-wt {B = A} X hα wfA)
          (convert↓At-wt {B = B} X hα wfB)
  convert↓At-wt {B = `∀ A} X hα (wf∀ wfA) =
    ⊢↓-∀ (convert↓At-wt {B = A} (suc X) (renameLookupᵗ suc hα) wfA)

------------------------------------------------------------------------
-- β-Λ preservation
------------------------------------------------------------------------

preserve-β-Λ :
  ∀ {Δ Ψ}{Σ : Store}{Γ : Ctx}{V : Term}{B T : Ty} →
  StoreWf Δ Ψ Σ →
  Value V →
  suc Δ ∣ Ψ ∣ ⟰ᵗ Σ ∣ ⤊ᵗ Γ ⊢ V ⦂ B →
  WfTy (suc Δ) Ψ B →
  WfTy Δ Ψ T →
  Δ ∣ suc Ψ ∣ ((length Σ , T) ∷ Σ) ∣ Γ ⊢
    ((V [ ｀ (length Σ) ]ᵀ) ↑ (convert↑ B (length Σ))) ⦂ B [ T ]ᵗ
preserve-β-Λ {Δ = Δ} {Ψ = Ψ} {Σ = Σ} {Γ = Γ}
  {V = V} {B = B} {T = T} wfΣ vV V⊢ wfB wfT =
  ⊢reveal c⊢ Vopen⊢↑
  where
    α = length Σ

    wfα : WfTy Δ (suc Ψ) (｀ α)
    wfα = wfSeal (len<suc-StoreWf wfΣ)

    Vopen⊢ :
      Δ ∣ suc Ψ ∣ Σ ∣ Γ ⊢ V [ ｀ α ]ᵀ ⦂ B [ ｀ α ]ᵗ
    Vopen⊢ = []ᵀ-fresh-∀-wt wfΣ V⊢

    Vopen⊢↑ :
      Δ ∣ suc Ψ ∣ ((α , T) ∷ Σ) ∣ Γ ⊢
        V [ ｀ α ]ᵀ ⦂ B [ ｀ α ]ᵗ
    Vopen⊢↑ = wk-term ≤-refl (drop ⊆ˢ-refl) Vopen⊢

    wfBα : WfTy Δ (suc Ψ) (B [ ｀ α ]ᵗ)
    wfBα =
      substᵗ-preserves-WfTy
        (WfTy-weakenˢ wfB (n≤1+n Ψ))
        (singleTyEnv-Wf (｀ α) wfα)

    c⊢ :
      Δ ∣ suc Ψ ∣ ((α , T) ∷ Σ) ⊢
        convert↑ B α ⦂ B [ ｀ α ]ᵗ ↑ˢ B [ T ]ᵗ
    c⊢ = convert↑At-wt {α = α} {T = T} {B = B} zero
      (Z∋ˢ refl refl)
      wfBα
