module proof.TypeSafety.Preservation where

-- File Charter:
--   * Type preservation for GTSFImp pure and store-changing reduction.
--   * Proves typing for structural reveal/conceal conversions generated by
--     allocation and the type equations needed by allocating steps.
--   * Exposes one-step and store-changing multi-step preservation for open
--     and closed terms.

open import Agda.Builtin.Equality using (_≡_; refl)
open import Data.List using ([]) renaming (_∷_ to _∷ᶜ_)
open import Data.Nat using (suc)
import Data.Fin as Fin
open import Data.Fin.Properties using (_≟_)
open import Relation.Binary.PropositionalEquality
  using (cong; sym; trans)
  renaming (subst to subst≡)
open import Relation.Nullary using (yes; no)

open import Types
open import TyStore
open import TermCtx hiding (_∋_⦂_)
open import Consistency
open import Conversion
open import Primitives
open import CastTerms
open import Reduction
open import proof.TypeInTermSubst
open import proof.TermInTermSubst
open import proof.ImprecisionConsistency using (fin-suc-injective)

------------------------------------------------------------------------
-- Structural reveal and conceal typing
------------------------------------------------------------------------

replaceEnv : ∀ {Δ} → TyVar Δ → Ty Δ → Δ ⇒ˢ Δ
replaceEnv X R Y with X ≟ Y
replaceEnv X R .X | yes refl = R
replaceEnv X R Y | no X≠Y = ＇ Y

replaceEnv-ext : ∀ {Δ} (X : TyVar Δ) (R : Ty Δ)
    (Y : TyVar (suc Δ))
  → replaceEnv (Fin.suc X) (⇑ᵗ R) Y ≡ extsᵗ (replaceEnv X R) Y
replaceEnv-ext X R Fin.zero = refl
replaceEnv-ext X R (Fin.suc Y) with X ≟ Y
replaceEnv-ext X R (Fin.suc .X) | yes refl = refl
replaceEnv-ext X R (Fin.suc Y) | no X≠Y = refl

mutual
  structural-reveal-typing : ∀ {Δ} {Σ : TyStore Δ} {X R}
      (B : Ty Δ)
    → Σ ∋ X ⦂ R
    → Σ ⊢↑[ X ⦂ R ] 〖 X , R ↑ B 〗
  structural-reveal-typing {X = X} (＇ Y) X∈ with X ≟ Y
  structural-reveal-typing {X = X} (＇ .X) X∈ | yes refl = ⊢↑-unseal X∈
  structural-reveal-typing {X = X} (＇ Y) X∈ | no X≠Y =
    ⊢↑-id-var X∈ X≠Y
  structural-reveal-typing (‵ ι) X∈ = ⊢↑-id-base X∈
  structural-reveal-typing ★ X∈ = ⊢↑-id-star X∈
  structural-reveal-typing (A ⇒ B) X∈ =
    ⊢↑-⇒ (structural-conceal-typing A X∈)
      (structural-reveal-typing B X∈)
  structural-reveal-typing (`∀ B) X∈ =
    ⊢↑-∀ refl (structural-reveal-typing B (S-lift∋ X∈ refl))

  structural-conceal-typing : ∀ {Δ} {Σ : TyStore Δ} {X R}
      (B : Ty Δ)
    → Σ ∋ X ⦂ R
    → Σ ⊢↓[ X ⦂ R ] makeConceal X R B
  structural-conceal-typing {X = X} (＇ Y) X∈ with X ≟ Y
  structural-conceal-typing {X = X} (＇ .X) X∈ | yes refl = ⊢↓-seal X∈
  structural-conceal-typing {X = X} (＇ Y) X∈ | no X≠Y =
    ⊢↓-id-var X∈ X≠Y
  structural-conceal-typing (‵ ι) X∈ = ⊢↓-id-base X∈
  structural-conceal-typing ★ X∈ = ⊢↓-id-star X∈
  structural-conceal-typing (A ⇒ B) X∈ =
    ⊢↓-⇒ (structural-reveal-typing A X∈)
      (structural-conceal-typing B X∈)
  structural-conceal-typing (`∀ B) X∈ =
    ⊢↓-∀ refl (structural-conceal-typing B (S-lift∋ X∈ refl))

replaceTy-subst : ∀ {Δ} (X : TyVar Δ) (R B : Ty Δ)
  → replaceTy X R B ≡ substᵗ (replaceEnv X R) B
replaceTy-subst X R (＇ Y) with X ≟ Y
replaceTy-subst X R (＇ .X) | yes refl = refl
replaceTy-subst X R (＇ Y) | no X≠Y = refl
replaceTy-subst X R (‵ ι) = refl
replaceTy-subst X R ★ = refl
replaceTy-subst X R (A ⇒ B)
  rewrite replaceTy-subst X R A | replaceTy-subst X R B = refl
replaceTy-subst X R (`∀ B) =
  cong `∀
    (trans (replaceTy-subst (Fin.suc X) (⇑ᵗ R) B)
      (substᵗ-cong B (replaceEnv-ext X R)))

replace-zero-open : ∀ {Δ} (B : Ty (suc Δ)) (C : Ty Δ)
  → replaceTy Fin.zero (⇑ᵗ C) B ≡ ⇑ᵗ (B [ C ]ᵗ)
replace-zero-open B C =
  trans (replaceTy-subst Fin.zero (⇑ᵗ C) B)
    (trans (substᵗ-cong B env-eq)
      (sym (renameᵗ-subst Fin.suc (singleSubᵗ C) B)))
  where
  env-eq : ∀ X
    → replaceEnv Fin.zero (⇑ᵗ C) X ≡
      renameᵗ Fin.suc (singleSubᵗ C X)
  env-eq Fin.zero = refl
  env-eq (Fin.suc X) = refl

reveal-zero-typing : ∀ {Δ} {Σ : TyStore Δ} {Γ : TermCtx (suc Δ)}
    {M : Term (suc Δ)}
    (B : Ty (suc Δ)) (C : Ty Δ)
  → ⟨ suc Δ , store-bind Σ C , Γ ⟩ ⊢ M ⦂ B
  → ⟨ suc Δ , store-bind Σ C , Γ ⟩
      ⊢ M ↑ 〖 Fin.zero , ⇑ᵗ C ↑ B 〗 ⦂ ⇑ᵗ (B [ C ]ᵗ)
reveal-zero-typing {Δ = Δ} {Σ = Σ} {Γ = Γ} {M = M} B C M⊢ =
  subst≡
    (λ T → ⟨ suc Δ , store-bind Σ C , Γ ⟩
      ⊢ M ↑ 〖 Fin.zero , ⇑ᵗ C ↑ B 〗 ⦂ T)
    (replace-zero-open B C)
    (⊢reveal (structural-reveal-typing B (Z∋ refl)) M⊢)

------------------------------------------------------------------------
-- Type equations for allocation
------------------------------------------------------------------------

applyBody-open-zero : ∀ {Δ} (B : Ty (suc Δ))
  → (renameᵗ (extᵗ Fin.suc) B) [ ＇ Fin.zero ]ᵗ ≡ B
applyBody-open-zero B =
  trans (substᵗ-rename (singleSubᵗ (＇ Fin.zero))
      (extᵗ Fin.suc) B)
    (trans (substᵗ-cong B env-eq) (substᵗ-id B))
  where
  env-eq : ∀ X
    → singleSubᵗ (＇ Fin.zero) (extᵗ Fin.suc X) ≡ ＇ X
  env-eq Fin.zero = refl
  env-eq (Fin.suc X) = refl

apply-open : ∀ {Δ Δ′} (chi : StoreChange Δ Δ′)
    (B : Ty (suc Δ)) (A : Ty Δ)
  → chi ▷ᵗ (B [ A ]ᵗ) ≡ (chi ▷ᵇ B) [ chi ▷ᵗ A ]ᵗ
apply-open keep B A = refl
apply-open (bind C) B A = rename-openᵗ Fin.suc B A

applyTermCtx : ∀ {Δ Δ′}
  → StoreChange Δ Δ′
  → TermCtx Δ
  → TermCtx Δ′
applyTermCtx keep Γ = Γ
applyTermCtx (bind C) Γ = ⇑ᶜ Γ

applyTermCtxs : ∀ {Δ Δ′}
  → StoreChanges Δ Δ′
  → TermCtx Δ
  → TermCtx Δ′
applyTermCtxs chis [] = []
applyTermCtxs chis (A ∷ᶜ Γ) =
  (chis ▶ᵗ A) ∷ᶜ applyTermCtxs chis Γ

applyTermCtxs-id : ∀ {Δ} (Γ : TermCtx Δ)
  → Γ ≡ applyTermCtxs [] Γ
applyTermCtxs-id [] = refl
applyTermCtxs-id (A ∷ᶜ Γ) =
  cong (A ∷ᶜ_) (applyTermCtxs-id Γ)

applyTermCtxs-step : ∀ {Δ Δ′ Δ″}
    (chi : StoreChange Δ Δ′)
    (chis : StoreChanges Δ′ Δ″)
    (Γ : TermCtx Δ)
  → applyTermCtxs chis (applyTermCtx chi Γ) ≡
      applyTermCtxs (chi ∷ chis) Γ
applyTermCtxs-step keep chis [] = refl
applyTermCtxs-step keep chis (A ∷ᶜ Γ) =
  cong (λ Γ′ → (chis ▶ᵗ A) ∷ᶜ Γ′)
    (applyTermCtxs-step keep chis Γ)
applyTermCtxs-step (bind C) chis [] = refl
applyTermCtxs-step (bind C) chis (A ∷ᶜ Γ) =
  cong (λ Γ′ → (chis ▶ᵗ ⇑ᵗ A) ∷ᶜ Γ′)
    (applyTermCtxs-step (bind C) chis Γ)

change-typing : ∀ {Δ Δ′} {Σ : TyStore Δ} {Γ : TermCtx Δ} {M A}
    (chi : StoreChange Δ Δ′)
  → ⟨ Δ , Σ , Γ ⟩ ⊢ M ⦂ A
  → ⟨ Δ′ , chi ▷ˢ Σ , applyTermCtx chi Γ ⟩
      ⊢ chi ▷ᵀ M ⦂ chi ▷ᵗ A
change-typing keep M⊢ = M⊢
change-typing (bind C) M⊢ = typing-shiftᵗ-bind M⊢

------------------------------------------------------------------------
-- Pure reduction
------------------------------------------------------------------------

pure-preservation : ∀ {Δ} {Σ : TyStore Δ} {Γ : TermCtx Δ}
    {M N : Term Δ} {A}
  → ⟨ Δ , Σ , Γ ⟩ ⊢ M ⦂ A
  → M —→ N
  → ⟨ Δ , Σ , Γ ⟩ ⊢ N ⦂ A
pure-preservation (⊢⊕ addℕ (⊢$ (κℕ m)) (⊢$ (κℕ n)))
    (δ-⊕ δ-add) = ⊢$ _
pure-preservation (⊢⊕ and𝔹 (⊢$ (κ𝔹 b)) (⊢$ (κ𝔹 c)))
    (δ-⊕ δ-and) = ⊢$ _
pure-preservation (⊢· (⊢ƛ N⊢) V⊢) (β vV) =
  typing-single-subst N⊢ V⊢
pure-preservation (⊢⟨⟩ V⊢ (id a)) (β-id vV) = V⊢
pure-preservation
    (⊢· (⊢⟨⟩ V⊢ (c ↦ d)) W⊢) (β-⇒ vV vW) =
  ⊢⟨⟩ (⊢· V⊢ (⊢⟨⟩ W⊢ c)) d
pure-preservation (⊢• (⊢⟨⟩ V⊢ (∀ᶜ c))) (β-∀ vV refl) =
  ⊢⟨⟩ (⊢• V⊢) (c [ _ ]ᶜ)
pure-preservation (⊢⟨⟩ V⊢ (c !)) (ground vV A≠G) =
  ⊢⟨⟩ (⊢⟨⟩ V⊢ c) ((idᵍ _) !)
pure-preservation (⊢⟨⟩ V⊢ (？ c)) (expand vV G≠B) =
  ⊢⟨⟩ (⊢⟨⟩ V⊢ (？ (idᵍ _))) c
pure-preservation (⊢⟨⟩ (⊢⟨⟩ V⊢ inject) project)
    (tag-untag vV) = V⊢
pure-preservation (⊢⟨⟩ (⊢⟨⟩ V⊢ inject) project)
    (tag-untag-bad vV G≠H) = ⊢blame
pure-preservation (⊢⟨⟩ V⊢ bot-intro)
    (blame-bot-intro vV) = ⊢blame
pure-preservation (⊢· (⊢reveal (⊢↑-⇒ c⊢ d⊢) V⊢) W⊢)
    (β-reveal-⇒ vV vW) =
  ⊢reveal d⊢ (⊢· V⊢ (⊢conceal c⊢ W⊢))
pure-preservation (⊢· (⊢conceal (⊢↓-⇒ c⊢ d⊢) V⊢) W⊢)
    (β-conceal-⇒ vV vW) =
  ⊢conceal d⊢ (⊢· V⊢ (⊢reveal c⊢ W⊢))
pure-preservation (⊢reveal (⊢↑-id-var X∈ X≢Y) V⊢)
    (id-reveal vV) = V⊢
pure-preservation (⊢reveal (⊢↑-id-base X∈) V⊢)
    (id-reveal vV) = V⊢
pure-preservation (⊢reveal (⊢↑-id-star X∈) V⊢)
    (id-reveal vV) = V⊢
pure-preservation (⊢conceal (⊢↓-id-var X∈ X≢Y) V⊢)
    (id-conceal vV) = V⊢
pure-preservation (⊢conceal (⊢↓-id-base X∈) V⊢)
    (id-conceal vV) = V⊢
pure-preservation (⊢conceal (⊢↓-id-star X∈) V⊢)
    (id-conceal vV) = V⊢
pure-preservation
    (⊢reveal (⊢↑-unseal X∈)
      (⊢conceal (⊢↓-seal X∈′) V⊢))
    (conceal-reveal vV) = V⊢
pure-preservation (⊢· ⊢blame M⊢) blame-·₁ = ⊢blame
pure-preservation (⊢· V⊢ ⊢blame) (blame-·₂ vV) = ⊢blame
pure-preservation (⊢• ⊢blame) blame-• = ⊢blame
pure-preservation (⊢⟨⟩ ⊢blame c) blame-⟨⟩ = ⊢blame
pure-preservation (⊢reveal c⊢ ⊢blame) blame-reveal = ⊢blame
pure-preservation (⊢conceal c⊢ ⊢blame) blame-conceal = ⊢blame
pure-preservation (⊢⊕ op ⊢blame M⊢) blame-⊕₁ = ⊢blame
pure-preservation (⊢⊕ op V⊢ ⊢blame) (blame-⊕₂ vV) = ⊢blame

------------------------------------------------------------------------
-- Store-changing one-step reduction
------------------------------------------------------------------------

preservation : ∀ {Δ Δ′} {Σ : TyStore Δ} {Γ : TermCtx Δ}
    {M : Term Δ}
    {N : Term Δ′} {A} {chi : StoreChange Δ Δ′}
  → ⟨ Δ , Σ , Γ ⟩ ⊢ M ⦂ A
  → M —→[ chi ] N
  → ⟨ Δ′ , chi ▷ˢ Σ , applyTermCtx chi Γ ⟩
      ⊢ N ⦂ chi ▷ᵗ A
preservation M⊢ (pure-step red) = pure-preservation M⊢ red
preservation (⊢• (⊢Λ vV V⊢)) (β-Λ vV′) =
  reveal-zero-typing _ _ (typing-lift-to-bind V⊢)
preservation {Δ = Δ} {Σ = Σ} {Γ = Γ}
    (⊢⟨⟩ V⊢ ((inst c) B≢★))
    (β-inst {V = V} {A = A} {B = B} vV .B≢★) =
  subst≡
    (λ T → ⟨ suc Δ , store-bind Σ ★ , ⇑ᶜ Γ ⟩
      ⊢ (⇑ᵗᵐ V ⦂∀ (bind ★ ▷ᵇ A) [ ＇ Fin.zero ]
          ↑ 〖 Fin.zero , ★ ↑ A 〗)
        ⟨ ↑ᶜ (c [ ★/0 ]ᶜ) ⟩ ⦂ T)
    (renameᵗ-wk-eq B)
    (⊢⟨⟩ before-cast⊢ (↑ᶜ (c [ ★/0 ]ᶜ)))
  where
  app⊢ = ⊢• (typing-shiftᵗ-bind V⊢)

  app⊢′ =
    subst≡
      (λ T → ⟨ suc Δ , store-bind Σ ★ , ⇑ᶜ Γ ⟩
        ⊢ ⇑ᵗᵐ V ⦂∀ (bind ★ ▷ᵇ A) [ ＇ Fin.zero ] ⦂ T)
      (applyBody-open-zero A) app⊢

  revealed⊢ = reveal-zero-typing A ★ app⊢′

  before-cast⊢ =
    subst≡
      (λ T → ⟨ suc Δ , store-bind Σ ★ , ⇑ᶜ Γ ⟩
        ⊢ (⇑ᵗᵐ V ⦂∀ (bind ★ ▷ᵇ A) [ ＇ Fin.zero ])
          ↑ 〖 Fin.zero , ★ ↑ A 〗 ⦂ T)
      (sym (renameᵗ-wk-eq (A [ ★ ]ᵗ))) revealed⊢
preservation (⊢• (⊢⟨⟩ V⊢ ((gen c) A≢★)))
    (β-gen vV .A≢★ safe) =
  reveal-zero-typing _ _ (⊢⟨⟩ (typing-shiftᵗ-bind V⊢) c)
preservation {Δ = Δ} {Σ = Σ} {Γ = Γ}
    (⊢• (⊢reveal (⊢↑-∀ eq c⊢) V⊢))
    (β-reveal-∀ {V = V} {A = A} {B = B} {C = C} vV) =
  reveal-zero-typing B A
    (⊢reveal (reveal-store-transport StoreTransport-lift-bind c⊢)
      applied⊢)
  where
  applied⊢ =
    subst≡
      (λ T → ⟨ suc Δ , store-bind Σ A , ⇑ᶜ Γ ⟩
        ⊢ ⇑ᵗᵐ V ⦂∀ (bind A ▷ᵇ C) [ ＇ Fin.zero ] ⦂ T)
      (applyBody-open-zero C) (⊢• (typing-shiftᵗ-bind V⊢))
preservation {Δ = Δ} {Σ = Σ} {Γ = Γ}
    (⊢• (⊢conceal (⊢↓-∀ eq c⊢) V⊢))
    (β-conceal-∀ {V = V} {A = A} {B = B} {C = C} vV) =
  reveal-zero-typing B A
    (⊢conceal (conceal-store-transport StoreTransport-lift-bind c⊢)
      applied⊢)
  where
  applied⊢ =
    subst≡
      (λ T → ⟨ suc Δ , store-bind Σ A , ⇑ᶜ Γ ⟩
        ⊢ ⇑ᵗᵐ V ⦂∀ (bind A ▷ᵇ C) [ ＇ Fin.zero ] ⦂ T)
      (applyBody-open-zero C) (⊢• (typing-shiftᵗ-bind V⊢))
preservation (⊢· L⊢ M⊢) (ξ-·₁ {χ = keep} red refl) =
  ⊢· (preservation L⊢ red) M⊢
preservation (⊢· L⊢ M⊢) (ξ-·₁ {χ = bind C} red refl) =
  ⊢· (preservation L⊢ red) (typing-shiftᵗ-bind M⊢)
preservation (⊢· V⊢ M⊢) (ξ-·₂ {χ = keep} vV red refl) =
  ⊢· V⊢ (preservation M⊢ red)
preservation (⊢· V⊢ M⊢) (ξ-·₂ {χ = bind C} vV red refl) =
  ⊢· (typing-shiftᵗ-bind V⊢) (preservation M⊢ red)
preservation (⊢• L⊢) (ξ-• {χ = keep} red refl refl) =
  ⊢• (preservation L⊢ red)
preservation (⊢• {C = C} {A = A} L⊢)
    (ξ-• {χ = bind D} {M′ = M′} red refl refl) =
  subst≡
    (λ T → _ ⊢ M′ ⦂∀ (bind D ▷ᵇ C) [ bind D ▷ᵗ A ] ⦂ T)
    (sym (apply-open (bind D) C A))
    (⊢• (preservation L⊢ red))
preservation (⊢⟨⟩ M⊢ c) (ξ-⟨⟩ {χ = chi} red refl) =
  ⊢⟨⟩ (preservation M⊢ red) (applyConsistency chi c)
preservation {Δ = Δ} {Σ = Σ} {Γ = Γ}
    (⊢reveal {A = A} {B = B} {c = c} c⊢ M⊢)
    (ξ-reveal {χ = keep} {M′ = M′} red refl) =
  subst≡
    (λ T → ⟨ Δ , Σ , Γ ⟩
      ⊢ M′ ↑ rename↑ (λ X → X) c ⦂ T)
    (renameᵗ-id B)
    (⊢reveal (reveal-rename-id c⊢)
      (subst≡ (λ T → ⟨ Δ , Σ , Γ ⟩ ⊢ M′ ⦂ T)
        (sym (renameᵗ-id A)) (preservation M⊢ red)))
preservation (⊢reveal c⊢ M⊢) (ξ-reveal {χ = bind C} red refl) =
  ⊢reveal (reveal-renameᵗ fin-suc-injective StoreRename-suc-bind c⊢)
    (preservation M⊢ red)
preservation {Δ = Δ} {Σ = Σ} {Γ = Γ}
    (⊢conceal {A = A} {B = B} {c = c} c⊢ M⊢)
    (ξ-conceal {χ = keep} {M′ = M′} red refl) =
  subst≡
    (λ T → ⟨ Δ , Σ , Γ ⟩
      ⊢ M′ ↓ rename↓ (λ X → X) c ⦂ T)
    (renameᵗ-id B)
    (⊢conceal (conceal-rename-id c⊢)
      (subst≡ (λ T → ⟨ Δ , Σ , Γ ⟩ ⊢ M′ ⦂ T)
        (sym (renameᵗ-id A)) (preservation M⊢ red)))
preservation (⊢conceal c⊢ M⊢) (ξ-conceal {χ = bind C} red refl) =
  ⊢conceal (conceal-renameᵗ fin-suc-injective StoreRename-suc-bind c⊢)
    (preservation M⊢ red)
preservation (⊢⊕ op L⊢ M⊢) (ξ-⊕₁ {χ = keep} red refl) =
  ⊢⊕ op (preservation L⊢ red) M⊢
preservation (⊢⊕ addℕ L⊢ M⊢) (ξ-⊕₁ {χ = bind C} red refl) =
  ⊢⊕ addℕ (preservation L⊢ red) (typing-shiftᵗ-bind M⊢)
preservation (⊢⊕ and𝔹 L⊢ M⊢) (ξ-⊕₁ {χ = bind C} red refl) =
  ⊢⊕ and𝔹 (preservation L⊢ red) (typing-shiftᵗ-bind M⊢)
preservation (⊢⊕ op V⊢ M⊢) (ξ-⊕₂ {χ = keep} vV red refl) =
  ⊢⊕ op V⊢ (preservation M⊢ red)
preservation (⊢⊕ addℕ V⊢ M⊢) (ξ-⊕₂ {χ = bind C} vV red refl) =
  ⊢⊕ addℕ (typing-shiftᵗ-bind V⊢) (preservation M⊢ red)
preservation (⊢⊕ and𝔹 V⊢ M⊢) (ξ-⊕₂ {χ = bind C} vV red refl) =
  ⊢⊕ and𝔹 (typing-shiftᵗ-bind V⊢) (preservation M⊢ red)

------------------------------------------------------------------------
-- Store-changing multi-step reduction
------------------------------------------------------------------------

multi-preservation : ∀ {Δ Δ′} {Σ : TyStore Δ} {Γ : TermCtx Δ}
    {M : Term Δ}
    {N : Term Δ′} {A} {chis : StoreChanges Δ Δ′}
  → ⟨ Δ , Σ , Γ ⟩ ⊢ M ⦂ A
  → M —↠[ chis ] N
  → ⟨ Δ′ , chis ▶ˢ Σ , applyTermCtxs chis Γ ⟩
      ⊢ N ⦂ chis ▶ᵗ A
multi-preservation {Δ = Δ} {Σ = Σ} {Γ = Γ} {M = M} {A = A}
    M⊢ ↠-refl =
  subst≡ (λ Γ′ → ⟨ Δ , Σ , Γ′ ⟩ ⊢ M ⦂ A)
    (applyTermCtxs-id Γ) M⊢
multi-preservation {Δ′ = Δ′} {Σ = Σ} {Γ = Γ} {N = N}
    {A = A} {chis = chi ∷ chis} M⊢ (↠-step red reds) =
  subst≡
    (λ Γ′ → ⟨ Δ′ , (chi ∷ chis) ▶ˢ Σ , Γ′ ⟩
      ⊢ N ⦂ (chi ∷ chis) ▶ᵗ A)
    (applyTermCtxs-step chi chis Γ)
    (multi-preservation (preservation M⊢ red) reds)
