module proof.DGG.Core.NuDGGStrictSpine where

-- File Charter:
--   * Aggregates the hole-free DGG spine and its terminal-trace support.
--   * Deliberately excludes the partial terminal proofs and active
--     catch-up/dispatcher scratch module.
--   * Provides a strict check target as proof components are promoted.

import proof.DGG.Core.NuDGGPreservation
import proof.DGG.Core.NuDGGSpine
import proof.DGG.Core.NuDGGClosedWorld
import proof.DGG.Core.NuDGGTerminal
import proof.DGG.TerminalBackward.NuDGGTerminalBackwardBlameAssembly
import proof.DGG.TerminalBackward.NuDGGTerminalBackwardValueDef
import proof.DGG.TerminalBackward.NuDGGTerminalBackwardValueWorldCoherentDef
import proof.DGG.TerminalBackward.NuDGGTerminalBackwardValueWorldCoherentProof
import proof.DGG.TerminalBackward.NuDGGTerminalBackwardValueProof
import proof.OneStep.NuImprecisionOneStepDef
import proof.NuCore.Misc.NuImprecisionValueCatchupDef
import proof.Catchup.Simulation.NuImprecisionSimulationResultDef
import proof.OneStep.NuImprecisionOneStepRelated
import proof.Store.Core.NuImprecisionStoreLift
import proof.Store.Prefix.NuImprecisionStorePrefix
import proof.WorldCoherent.Core.NuImprecisionWorldCoherenceDef
import proof.WorldCoherent.Core.NuImprecisionWorldCoherenceProof
import proof.WorldCoherent.Core.NuImprecisionWorldCoherenceLemma
import proof.WorldCoherent.Core.NuImprecisionWorldCoherenceCrossedLemma
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentResultDef
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentOneStepDef
import proof.WorldCoherent.Value.NuImprecisionWorldCoherentValueCatchupDef
import proof.WorldCoherent.Value.NuImprecisionWorldCoherentValueCatchupPrefixDef
import proof.WorldCoherent.Value.NuImprecisionWorldCoherentValueCatchupProof
import proof.WorldCoherent.Value.NuImprecisionWorldCoherentValueCatchupPrefixProof
import proof.WorldCoherent.Source.RuntimeSteps.NuImprecisionWorldCoherentSourceRuntimeCatchupDef
import proof.WorldCoherent.Source.RevealConceal.NuImprecisionWorldCoherentSourceConcealCatchup
import proof.WorldCoherent.Quotient.InstCatchup.NuImprecisionWorldCoherentQuotientInstCatchupDef
import proof.WorldCoherent.Quotient.Core.NuImprecisionWorldCoherentQuotientRepresentativeInstCatchupDef
import proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCatchupDef
import
  proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Core.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.View.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Core.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCastWidenCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCastWidenCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedGenDownCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedGenDownCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Paired.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupLemma
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCastWidenCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCastWidenCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceGenDownCatchupDef
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceGenDownCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.Source.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupLemma
import
  proof.WorldCoherent.Quotient.InstPathIdentity.View.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupProof
import
  proof.WorldCoherent.Quotient.InstPathIdentity.View.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupLemma
import
  proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepCatchupDef
import
  proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepViewCatchupDef
import
  proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepCatchupProof
import
  proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathTargetStepCatchupDef
import proof.Quotient.NuImprecisionQuotientInstPathProperties
import proof.WorldCoherent.Quotient.InstPath.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCasesProof
import proof.WorldCoherent.Quotient.InstCatchup.NuImprecisionWorldCoherentQuotientInstCatchupLemma
import proof.Core.Properties.NuCastImprecision
import proof.WorldCoherent.Source.CastCatchup.NuImprecisionWorldCoherentSourceInertWidenFrameDef
import proof.WorldCoherent.Source.CastCatchup.NuImprecisionWorldCoherentSourceInertWidenFrameLemma
import proof.WorldCoherent.Quotient.InstFunTag.NuImprecisionWorldCoherentQuotientInstFunTagCatchupDef
import proof.WorldCoherent.Quotient.InstFunTag.NuImprecisionWorldCoherentQuotientInstFunTagCatchupProof
import proof.WorldCoherent.Quotient.InstFunTag.NuImprecisionWorldCoherentQuotientInstFunTagCatchupLemma
import proof.WorldCoherent.Quotient.Final.NuImprecisionWorldCoherentQuotientClassificationDef
import proof.WorldCoherent.Quotient.Final.NuImprecisionWorldCoherentQuotientFinalCatchupDef
import proof.WorldCoherent.Quotient.Final.NuImprecisionWorldCoherentQuotientFinalCatchupProof
import proof.WorldCoherent.Quotient.Final.NuImprecisionWorldCoherentQuotientFinalCatchupLemma
import proof.Target.SealTag.NuImprecisionTargetSealCancellationDef
import proof.Source.SealTag.NuImprecisionSourceSealCancellationDef
import proof.WorldCoherent.Source.RevealConceal.NuImprecisionWorldCoherentSourceUnsealCatchupDef
import proof.Target.SealTag.NuImprecisionTargetSealCancellationProof
import proof.Target.SealTag.NuImprecisionTargetSealCancellationLemma
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentTargetRevealRootDef
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentTargetRevealRootProof
import proof.DGG.Core.NuDGGTraceAlignment
import proof.DGG.Core.NuDGGTraceMeasure
import proof.DGG.Core.NuDGGWeakResultPreservation
import proof.Catchup.Core.NuImprecisionCatchupPrefixSupport
import proof.Catchup.Core.NuImprecisionCatchupQuotientSupport
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentCatchupComposition
import proof.WorldCoherent.Core.NuImprecisionWorldCoherentCatchupPrefixFrames
import proof.Catchup.Core.NuImprecisionCatchupSourceAllocationTerminal
import proof.Catchup.Core.NuImprecisionCatchupSourceCastTerminal
import proof.OneStep.NuImprecisionOneStepSourceCastFrames
import proof.OneStep.NuImprecisionOneStepSourceConversionFrames
import proof.OneStep.NuImprecisionOneStepPrimitiveFrames
import proof.OneStep.NuImprecisionOneStepPrimitiveLeaves
import proof.OneStep.NuImprecisionOneStepApplicationRoots
import proof.OneStep.NuImprecisionOneStepTargetBlameRoots
import proof.OneStep.NuImprecisionAtomicTargetReindex
import proof.OneStep.NuImprecisionOneStepTargetCastIdentityRoots
import proof.Target.Core.NuImprecisionTargetCastSequenceMidpointDef
import proof.OneStep.NuImprecisionOneStepTargetCastSequenceRoots
import proof.OneStep.NuImprecisionOneStepTargetCastFrames
import proof.OneStep.NuImprecisionOneStepTargetConversionFrames
import proof.Quotient.NuImprecisionQuotientInstView
import proof.Target.Core.NuImprecisionTargetBlameCatchup
