module proof.NuDGGStrictSpine where

-- File Charter:
--   * Aggregates the hole-free DGG spine and its terminal-trace support.
--   * Deliberately excludes the partial terminal proofs and active
--     catch-up/dispatcher scratch module.
--   * Provides a strict check target as proof components are promoted.

import proof.NuDGGPreservation
import proof.NuDGGSpine
import proof.NuDGGClosedWorld
import proof.NuDGGTerminal
import proof.NuDGGTerminalBackwardBlameAssembly
import proof.NuDGGTerminalBackwardValueDef
import proof.NuDGGTerminalBackwardValueWorldCoherentDef
import proof.NuDGGTerminalBackwardValueWorldCoherentProof
import proof.NuDGGTerminalBackwardValueProof
import proof.NuImprecisionOneStepDef
import proof.NuImprecisionValueCatchupDef
import proof.NuImprecisionSimulationResultDef
import proof.NuImprecisionOneStepRelated
import proof.NuImprecisionStoreLift
import proof.NuImprecisionStorePrefix
import proof.NuImprecisionWorldCoherenceDef
import proof.NuImprecisionWorldCoherenceProof
import proof.NuImprecisionWorldCoherenceLemma
import proof.NuImprecisionWorldCoherenceCrossedLemma
import proof.NuImprecisionWorldCoherentResultDef
import proof.NuImprecisionWorldCoherentOneStepDef
import proof.NuImprecisionWorldCoherentValueCatchupDef
import proof.NuImprecisionWorldCoherentValueCatchupPrefixDef
import proof.NuImprecisionWorldCoherentValueCatchupProof
import proof.NuImprecisionWorldCoherentValueCatchupPrefixProof
import proof.NuImprecisionWorldCoherentSourceRuntimeCatchupDef
import proof.NuImprecisionWorldCoherentSourceConcealCatchup
import proof.NuImprecisionWorldCoherentQuotientInstCatchupDef
import proof.NuImprecisionWorldCoherentQuotientRepresentativeInstCatchupDef
import proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCastWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCastWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedIdDownCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedGenDownCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedGenDownCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityPairedCatchupLemma
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCastWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCastWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceIdDownCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceGenDownCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceGenDownCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentitySourceCatchupLemma
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathIdentityViewCatchupLemma
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepViewCatchupDef
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathSourceStepCatchupProof
import
  proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathTargetStepCatchupDef
import proof.NuImprecisionQuotientInstPathProperties
import proof.NuImprecisionWorldCoherentQuotientRepresentativeInstPathCasesProof
import proof.NuImprecisionWorldCoherentQuotientInstCatchupLemma
import proof.NuCastImprecision
import proof.NuImprecisionWorldCoherentSourceInertWidenFrameDef
import proof.NuImprecisionWorldCoherentSourceInertWidenFrameLemma
import proof.NuImprecisionWorldCoherentQuotientInstFunTagCatchupDef
import proof.NuImprecisionWorldCoherentQuotientInstFunTagCatchupProof
import proof.NuImprecisionWorldCoherentQuotientInstFunTagCatchupLemma
import proof.NuImprecisionWorldCoherentQuotientClassificationDef
import proof.NuImprecisionWorldCoherentQuotientFinalCatchupDef
import proof.NuImprecisionWorldCoherentQuotientFinalCatchupProof
import proof.NuImprecisionWorldCoherentQuotientFinalCatchupLemma
import proof.NuImprecisionTargetSealCancellationDef
import proof.NuImprecisionSourceSealCancellationDef
import proof.NuImprecisionWorldCoherentSourceUnsealCatchupDef
import proof.NuImprecisionTargetSealCancellationProof
import proof.NuImprecisionTargetSealCancellationLemma
import proof.NuImprecisionWorldCoherentTargetRevealRootDef
import proof.NuImprecisionWorldCoherentTargetRevealRootProof
import proof.NuDGGTraceAlignment
import proof.NuDGGTraceMeasure
import proof.NuDGGWeakResultPreservation
import proof.NuImprecisionCatchupPrefixSupport
import proof.NuImprecisionCatchupQuotientSupport
import proof.NuImprecisionWorldCoherentCatchupComposition
import proof.NuImprecisionWorldCoherentCatchupPrefixFrames
import proof.NuImprecisionCatchupSourceAllocationTerminal
import proof.NuImprecisionCatchupSourceCastTerminal
import proof.NuImprecisionOneStepSourceCastFrames
import proof.NuImprecisionOneStepSourceConversionFrames
import proof.NuImprecisionOneStepPrimitiveFrames
import proof.NuImprecisionOneStepPrimitiveLeaves
import proof.NuImprecisionOneStepApplicationRoots
import proof.NuImprecisionOneStepTargetBlameRoots
import proof.NuImprecisionAtomicTargetReindex
import proof.NuImprecisionOneStepTargetCastIdentityRoots
import proof.NuImprecisionTargetCastSequenceMidpointDef
import proof.NuImprecisionOneStepTargetCastSequenceRoots
import proof.NuImprecisionOneStepTargetCastFrames
import proof.NuImprecisionOneStepTargetConversionFrames
import proof.NuImprecisionQuotientInstView
import proof.NuImprecisionTargetBlameCatchup
