module proof.NuImprecisionPairedTargetClosingStrictSpine where

-- File Charter:
--   * Aggregates the strict paired-index allocation and target-closing
--     architecture used by source `ν` and runtime `ν ★` catch-up.
--   * Provides a focused integration check below `NuDGGStrictSpine` and
--     `All.agda`; it imports statements and higher-order proofs, not missing
--     canonical `Lemma` assemblies.
--   * Deliberately excludes the broad simulation modules and permissive
--     scratch development.

import proof.NuImprecisionPairedLambdaTargetClosingRelationCounterexample
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewDef
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewProof
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewProperties
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersDef
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameDef
import proof.NuImprecisionPairedLambdaTargetClosingFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingAssemblyProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaConversionRotationCounterexample
import
  proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationDef
import proof.NuImprecisionFreshTypePath
import
  proof.NuImprecisionPairedUniversalConversionFreshPathCycleDef
import
  proof.NuImprecisionPairedUniversalConversionFreshPathCycleProof
import
  proof.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafPairedConversionCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafAllIndexClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationProof
import proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFramePairedConversionCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameAllIndexClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationDef
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationFrameClosingDef
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewDef
import proof.NuImprecisionSourceNuPairedBinderSupport
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupProof
import
  proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupProof
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentLeftCatchupPrependKeepStep
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstPostBetaCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealSpineWidenCatchupDef
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaUnsealClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllWideningTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupDef
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupProof
