module proof.NuImprecisionPairedTargetClosingStrictSpine where

-- File Charter:
--   * Aggregates the strict paired-index allocation and target-closing
--     architecture used by source `ν` and runtime `ν ★` catch-up.
--   * Provides a focused integration check below `NuDGGStrictSpine` and
--     `All.agda`; it imports statements and higher-order proofs, not missing
--     canonical `Lemma` assemblies.
--   * Deliberately excludes the broad simulation modules and permissive
--     scratch development.

import proof.NuImprecisionPairedLambdaTargetClosingRelationCounterexample
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationDef
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationViewDef
import proof.NuImprecisionSourceNuPairedBinderSupport
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupProof
import
  proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupProof
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentLeftCatchupPrependKeepStep
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstPostBetaCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealSpineWidenCatchupDef
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaUnsealClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllWideningTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupDef
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupProof
