module proof.NuImprecisionQuotientToOrdinaryCounterexample where

-- File Charter:
--   * Records the strict obstruction to deriving quotient-inst catch-up from
--     the current ordinary source-runtime and allocation interfaces.
--   * Exhibits a source-exclusive quotient-inst endpoint whose quotient
--     relation is generated by a genuine adjacent-forall permutation.
--   * Proves that the corresponding ordinary pre-inst imprecision relation
--     required by the existing source-widen path does not exist.

open import Agda.Builtin.Equality using (refl)
open import Data.Empty using (⊥)
open import Data.List using ([]; _∷_)
open import Data.List.Membership.Propositional using (_∈_)
open import Data.List.Relation.Unary.Any using (here; there)
open import Data.Nat using (zero; suc; z<s)
open import Data.Product using (_×_; _,_; proj₂)

open import ForallPermutation using
  ( _≈∀_
  ; _∣_⊢_⊑ᵖ_⊣_
  ; ≈∀-refl
  ; ≈∀-swap
  ; quotientᵖ
  )
open import ImprecisionWf using
  ( _ˣ⊑ˣ_
  ; ⇑ᵢ
  ; _∣_⊢_⊑_⊣_
  ; idˣ
  ; ∀ⁱ_
  ; ν
  )
open import Types using (`∀; ＇_)
open import proof.NuImprecisionContextExclusivityDef using
  (SourceNameExclusive)


private
  no-swapped-match :
    (suc zero ˣ⊑ˣ zero) ∈
      ((zero ˣ⊑ˣ zero) ∷
       ⇑ᵢ ((zero ˣ⊑ˣ zero) ∷ [])) →
    ⊥
  no-swapped-match (here ())
  no-swapped-match (there (here ()))
  no-swapped-match (there (there ()))


swap-quotient-survives-source-exclusivityᵀ :
  SourceNameExclusive [] ×
  ([] ∣ zero ⊢
    `∀ (`∀ (＇ (suc zero))) ⊑ᵖ `∀ (`∀ (＇ zero)) ⊣ zero)
swap-quotient-survives-source-exclusivityᵀ =
  (λ ()) ,
  quotientᵖ ≈∀-swap
    (∀ⁱ (∀ⁱ (idˣ (here refl) z<s z<s)))
    ≈∀-refl


swap-quotient-has-no-ordinary-pre-inst-relationᵀ :
  [] ∣ zero ⊢
    `∀ (`∀ (＇ (suc zero))) ⊑ `∀ (`∀ (＇ zero)) ⊣ zero →
  ⊥
swap-quotient-has-no-ordinary-pre-inst-relationᵀ
    (∀ⁱ (∀ⁱ (idˣ match 1<2 0<2))) =
  no-swapped-match match
swap-quotient-has-no-ordinary-pre-inst-relationᵀ
    (∀ⁱ (ν () inner))
swap-quotient-has-no-ordinary-pre-inst-relationᵀ
    (ν occ (∀ⁱ ()))
swap-quotient-has-no-ordinary-pre-inst-relationᵀ
    (ν occ (ν () inner))


no-global-quotient-to-ordinary-alignmentᵀ :
  (∀ {Φ Δᴸ Δᴿ A B} →
    Φ ∣ Δᴸ ⊢ A ⊑ᵖ B ⊣ Δᴿ →
    Φ ∣ Δᴸ ⊢ A ⊑ B ⊣ Δᴿ) →
  ⊥
no-global-quotient-to-ordinary-alignmentᵀ align =
  swap-quotient-has-no-ordinary-pre-inst-relationᵀ
    (align (proj₂ swap-quotient-survives-source-exclusivityᵀ))
