module proof.NuImprecisionPairedTargetClosingStrictSpine where

-- File Charter:
--   * Aggregates the strict paired-index allocation and target-closing
--     architecture used by source `ν` and runtime `ν ★` catch-up.
--   * Provides a focused integration check below `NuDGGStrictSpine` and
--     `All.agda`; it imports statements and higher-order proofs, not missing
--     canonical `Lemma` assemblies.
--   * Deliberately excludes the broad simulation modules and permissive
--     scratch development.

import proof.NuImprecisionPairedLambdaTargetClosingRelationCounterexample
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewDef
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewProof
import proof.NuImprecisionPairedLambdaTargetClosingFrameViewProperties
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPendingTargetFramesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPendingTargetMaterializationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPendingTargetMaterializationProof
import proof.NuImprecisionPairedLambdaTargetClosingNuTerminalDef
import proof.NuImprecisionPairedLambdaTargetClosingNuTerminalProof
import proof.NuImprecisionPairedLambdaTargetClosingAllTerminalDef
import proof.NuImprecisionPairedLambdaTargetClosingMaterializedTerminalDef
import proof.NuImprecisionPairedLambdaTargetClosingMaterializedTerminalProof
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationValueTerminalProof
import proof.NuImprecisionPairedLambdaTargetClosingContinuationFromViewDef
import proof.NuImprecisionPairedLambdaTargetClosingContinuationFromViewProof
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationHandlersDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationLambdaLambdaLeafDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationLambdaLeafDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationGenNuLeafDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationUpGenLeafDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationSourceGenFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllNarrowingFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllWideningFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllRevealFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationSourceAllConcealFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationPairedConversionFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationPairedWideningFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationUpIdFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationUpGenAllFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingContinuationHandlersAssemblyProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameDef
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetFrameProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetRevealCoreDef
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingTargetRevealProof
import proof.NuImprecisionPairedLambdaTargetClosingFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingHandlersProof
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingCapabilitiesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingFrameClosingAssemblyProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaConversionRotationCounterexample
import
  proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationDef
import proof.NuImprecisionFreshTypePath
import proof.NuImprecisionFreshTypePathTransport
import
  proof.NuImprecisionPairedUniversalConversionFreshPathSquareDef
import
  proof.NuImprecisionPairedUniversalConversionFreshPathTargetHalfSquareDef
import
  proof.NuImprecisionPairedUniversalConversionFreshPathTargetStructuralHalfSquareDef
import
  proof.NuImprecisionPairedUniversalConversionFreshPathTargetHalfSquareProof
import
  proof.NuImprecisionPairedUniversalConversionFreshPathSquareProof
import
  proof.NuImprecisionPairedUniversalConversionFreshPathCycleDef
import
  proof.NuImprecisionPairedUniversalConversionFreshPathCycleProof
import
  proof.NuImprecisionPairedLambdaTargetClosingNuPairedConversionRotationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafPairedConversionCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralRevealClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafStructuralConcealClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafPairedConversionCasesProof
import
  proof.NuImprecisionPairedLambdaTargetClosingLambdaLambdaLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafAllIndexClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenLeafClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuConversionRotationProof
import proof.NuImprecisionPairedLambdaTargetClosingGenLeafNuClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFramePairedConversionCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingCoreDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralRevealClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameStructuralConcealClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFramePairedConversionCasesProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameCommutationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceGenFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameAllIndexClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameCommutationProof
import
  proof.NuImprecisionPairedLambdaTargetClosingSourceAllFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedConversionFramePairedConversionCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedConversionFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleSourceInertCoreDef
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameCompatibleSourceInertProof
import
  proof.NuImprecisionPairedLambdaTargetClosingPairedWideningFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpIdFrameWideningCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpIdFrameClosingProof
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameWideningCasesDef
import
  proof.NuImprecisionPairedLambdaTargetClosingUpGenAllFrameClosingProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationDef
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationFrameClosingDef
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAssemblyProof
import
  proof.NuImprecisionSourceNuPairedAllConversionPostBetaAllRevealClosingRelationAmbientViewDef
import proof.NuImprecisionSourceNuPairedBinderSupport
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexCatchupProof
import
  proof.NuImprecisionWorldCoherentFinalSourceNuCastPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupDef
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexCatchupProof
import proof.NuImprecisionWorldCoherentFinalSourceNuPairedIndexViewCatchupDef
import proof.NuImprecisionWorldCoherentLeftCatchupPrependKeepStep
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllRevealRelationSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingAllWidenCatchupSourceViewDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstPostBetaCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingInstWidenCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingRevealCatchupProof
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealCatchupProof
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingUnsealSpineWidenCatchupDef
import proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupDef
import
  proof.NuImprecisionWorldCoherentPairedLambdaTargetClosingWidenCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuCastPairedLambdaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaTargetClosingCatchupAssemblyProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionPostBetaUnsealClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllConversionTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllTargetClosingCatchupAssemblyProof
import
  proof.NuImprecisionWorldCoherentSourceNuPairedAllWideningTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupDef
import
  proof.NuImprecisionWorldCoherentSourceNuPairedLambdaTargetClosingCatchupProof
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupDef
import proof.NuImprecisionWorldCoherentTargetInertFrameCatchupProof
